#requires -Version 5.1

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$CaptureCandidateDirectory,
    [Parameter(Mandatory=$true)][string]$PipelineCommitPath,
    [Parameter(Mandatory=$true)][string]$DestinationDirectory,
    [Parameter(Mandatory=$true)][string]$EvidenceRoot,
    [Parameter(Mandatory=$true)][string]$RepositoryRoot
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'RendererCompatibility.Common.ps1')

function Resolve-FinalContained([string]$Root,[string]$Path,[string]$Context){$full=if([IO.Path]::IsPathRooted($Path)){[IO.Path]::GetFullPath($Path)}else{[IO.Path]::GetFullPath((Join-Path $Root $Path))};if($full-cne$Root-and-not$full.StartsWith($Root+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)){throw "$Context escaped its evidence root."};Assert-RendererNonReparsePath $Root $full $Context;$full}
function Read-FinalJson([string]$Root,[string]$Path,[string]$Context,[string]$Repo){$read=Get-RendererStableFileIdentity $Root $Path $Context -IncludeBytes -KeepOpen;try{$json=(New-Object Text.UTF8Encoding($false,$true)).GetString($read.Content);$value=ConvertFrom-StrictHumanDesignReviewJson $json $Context;if($PSVersionTable.PSVersion.Major-ge7-and(Get-Command ConvertFrom-Json).Parameters.ContainsKey('DateKind')){$value=$json|ConvertFrom-Json -DateKind String};$canonical=ConvertTo-RendererCanonicalJson $value $Repo;if($json-cne($canonical+"`n")){throw "$Context must be exact canonical JCS plus exactly one LF."};[pscustomobject]@{Value=$value;Stable=$read;CanonicalSha256=(Get-HumanDesignReviewSha256ForText $canonical)}}catch{if($null-ne$read.Stream){$read.Stream.Dispose()};throw}}
function New-FinalJsonBinding($Read,[string]$Relative){[pscustomobject][ordered]@{relativePath=$Relative.Replace('\','/');bytes=[long]$Read.Stable.Bytes;fileSha256=[string]$Read.Stable.Sha256;canonicalSha256=[string]$Read.CanonicalSha256}}
function Remove-FinalOwnedTree($Lease,[string]$Parent,[string]$Path){Assert-RendererDirectoryLease $Lease $Parent $Path 'Finalizer owned staging cleanup';$items=@(Get-ChildItem -LiteralPath $Path -Recurse -Force);foreach($item in $items){if(($item.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){throw 'Finalizer owned staging cleanup encountered a reparse point.'}};foreach($file in @($items|Where-Object{-not$_.PSIsContainer})){[IO.File]::Delete($file.FullName)};foreach($dir in @($items|Where-Object{$_.PSIsContainer}|Sort-Object{$_.FullName.Length}-Descending)){[IO.Directory]::Delete($dir.FullName,$false)};Assert-RendererDirectoryLease $Lease $Parent $Path 'Finalizer owned staging cleanup after children';[RendererCompatibility.NativePath]::DeleteDirectory($Lease.Handle);$Lease.DeletePending=$true;$Lease.Handle.Dispose()}

$root=[IO.Path]::GetFullPath($EvidenceRoot).TrimEnd('\','/');$repo=[IO.Path]::GetFullPath($RepositoryRoot);Assert-RendererNonReparsePath $root $root 'Finalizer evidence root'
$capture=Resolve-FinalContained $root $CaptureCandidateDirectory 'Capture candidate directory';$commitPath=Resolve-FinalContained $root $PipelineCommitPath 'Pipeline transaction commit';$destination=Resolve-FinalContained $root $DestinationDirectory 'Final renderer evidence directory'
if(-not(Test-Path -LiteralPath $capture -PathType Container)){throw 'Capture candidate directory is missing.'};if(Test-Path -LiteralPath $destination){throw 'Final renderer evidence directory already exists; refusing to clobber.'}
foreach($pair in @(@($capture,$destination),@($commitPath,$destination))){if($pair[0]-ceq$pair[1]-or$pair[0].StartsWith($pair[1]+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)-or$pair[1].StartsWith($pair[0]+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)){throw 'Finalizer input/output paths must be distinct and non-overlapping.'}}
if($commitPath-ceq$capture-or$commitPath.StartsWith($capture+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)){throw 'Capture candidate and pipeline commit authority must be disjoint.'}
$captureManifestPath=Join-Path $capture 'v0.2-renderer-compatibility-manifest.json';$captureManifestStable=Get-RendererStableFileIdentity $capture $captureManifestPath 'Capture candidate manifest' -IncludeBytes -KeepOpen
$pipeline=$null;$sourceReads=@{};$captureLeases=@([pscustomobject]@{Path=$captureManifestPath;Stable=$captureManifestStable});$stage=$null;$stageLease=$null;$committed=$false
try{
    $captureResult=Test-RendererCompatibilityManifest $captureManifestPath $capture $repo -ValidateBindings
    $captureManifestJson=(New-Object Text.UTF8Encoding($false,$true)).GetString($captureManifestStable.Content);$captureManifest=ConvertFrom-StrictHumanDesignReviewJson $captureManifestJson 'Capture candidate manifest';if($PSVersionTable.PSVersion.Major-ge7-and(Get-Command ConvertFrom-Json).Parameters.ContainsKey('DateKind')){$captureManifest=$captureManifestJson|ConvertFrom-Json -DateKind String}
    if([long]$captureManifest.manifestVersion-ne4-or$captureManifest.performanceProtocol.samplesStatus-cne'NOT_OBSERVED'-or$null-ne$captureManifest.performanceProtocol.evidenceReceipt-or$null-ne$captureManifest.performanceProtocol.pipelineCommit){throw 'Finalizer requires an unfinalized manifest-v4 performance-only capture candidate.'}
    $pipeline=Read-FinalJson $root $commitPath 'Pipeline transaction commit' $repo
    $p=$pipeline.Value;Assert-RendererExactProperties $p @('schemaVersion','kind','runNonce','capturePackageRootPath','source','files','evidenceBoundary') 'Pipeline transaction commit';$null=Resolve-RendererHistoricalPackageRoot $p.capturePackageRootPath 'Pipeline capture package root';Assert-RendererExactProperties $p.source @('commitSha','treeSha') 'Pipeline source';Assert-RendererExactProperties $p.files @('raw','binding','performanceCommit','performanceReceipt') 'Pipeline files';Assert-RendererExactProperties $p.evidenceBoundary @('actualHerdrRuntime','release','creditGranted') 'Pipeline boundary';Assert-RendererBoolean $p.evidenceBoundary.creditGranted 'Pipeline creditGranted'
    if([long]$p.schemaVersion-ne4-or$p.kind-cne'issue149-performance-pipeline-commit'-or$p.runNonce-cnotmatch'^[0-9a-f]{32}$'-or$p.source.commitSha-cne$captureManifest.candidate.source.commitSha-or$p.source.treeSha-cne$captureManifest.candidate.source.treeSha-or$p.evidenceBoundary.actualHerdrRuntime-cne'NOT_OBSERVED'-or$p.evidenceBoundary.release-cne'NOT_OBSERVED'-or[bool]$p.evidenceBoundary.creditGranted){throw 'Pipeline transaction commit does not bind the capture candidate or preserve no-credit boundaries.'}
    foreach($name in @('raw','binding','performanceCommit','performanceReceipt')){$binding=$p.files.$name;Assert-RendererExactProperties $binding @('relativePath','bytes','sha256') "Pipeline $name";Assert-RendererRelativePath $binding.relativePath "Pipeline $name path";Assert-RendererPositiveInteger $binding.bytes "Pipeline $name bytes";Assert-RendererSha $binding.sha256 "Pipeline $name SHA";$path=Resolve-RendererBoundPath $root $binding.relativePath "Pipeline $name";$stable=Get-RendererStableFileIdentity $root $path "Pipeline $name" -IncludeBytes -KeepOpen;if($stable.Bytes-ne[long]$binding.bytes-or$stable.Sha256-cne$binding.sha256){$stable.Stream.Dispose();throw "Pipeline $name binding failed."};$sourceReads[$name]=[pscustomobject]@{Path=$path;Stable=$stable;Binding=$binding}}
    $stageParent=Split-Path -Parent $destination;$stage=Join-Path $stageParent ('.renderer-final-stage-'+[Guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Path $stage|Out-Null;$stageLease=Open-RendererDirectoryLease $stageParent $stage 'Finalizer owned staging directory' -AllowDelete
    $captureItems=@(Get-ChildItem -LiteralPath $capture -Recurse -Force);foreach($item in $captureItems){if(($item.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){throw 'Capture candidate contains a reparse point.'};$relative=$item.FullName.Substring($capture.Length).TrimStart('\','/');$target=Join-Path $stage $relative;if($item.PSIsContainer){New-Item -ItemType Directory -Path $target|Out-Null}else{$held=if($item.FullName-ceq$captureManifestPath){$captureManifestStable}else{Get-RendererStableFileIdentity $capture $item.FullName "Capture candidate $relative" -IncludeBytes -KeepOpen};if($item.FullName-cne$captureManifestPath){$captureLeases+=,[pscustomobject]@{Path=$item.FullName;Stable=$held}};$parent=Split-Path -Parent $target;if(-not(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};$stream=[IO.File]::Open($target,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);try{$stream.Write($held.Content,0,$held.Content.Length);$stream.Flush($true)}finally{$stream.Dispose()}}}
    foreach($name in $sourceReads.Keys){$relative=[string]$sourceReads[$name].Binding.relativePath;$target=Join-Path $stage $relative;if(Test-Path -LiteralPath $target){throw "Final evidence path collision for pipeline $name."};$parent=Split-Path -Parent $target;if(-not(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};$bytes=$sourceReads[$name].Stable.Content;$stream=[IO.File]::Open($target,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);try{$stream.Write($bytes,0,$bytes.Length);$stream.Flush($true)}finally{$stream.Dispose()};$copied=Get-RendererStableFileIdentity $stage $target "Copied pipeline $name";if($copied.Bytes-ne$sourceReads[$name].Stable.Bytes-or$copied.Sha256-cne$sourceReads[$name].Stable.Sha256){throw "Copied pipeline $name changed."}}
    $commitRelative=$commitPath.Substring($root.Length).TrimStart('\','/').Replace('\','/');$commitTarget=Join-Path $stage $commitRelative;if(Test-Path -LiteralPath $commitTarget){throw 'Final evidence pipeline commit path collision.'};$commitParent=Split-Path -Parent $commitTarget;if(-not(Test-Path -LiteralPath $commitParent)){New-Item -ItemType Directory -Path $commitParent -Force|Out-Null};$stream=[IO.File]::Open($commitTarget,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);try{$stream.Write($pipeline.Stable.Content,0,$pipeline.Stable.Content.Length);$stream.Flush($true)}finally{$stream.Dispose()}
    $selectedJson=(New-Object Text.UTF8Encoding($false,$true)).GetString($sourceReads.performanceReceipt.Stable.Content);$selectedValue=ConvertFrom-StrictHumanDesignReviewJson $selectedJson 'Selected performance receipt';if($PSVersionTable.PSVersion.Major-ge7-and(Get-Command ConvertFrom-Json).Parameters.ContainsKey('DateKind')){$selectedValue=$selectedJson|ConvertFrom-Json -DateKind String};$selectedCanonical=Get-HumanDesignReviewSha256ForText (ConvertTo-RendererCanonicalJson $selectedValue $repo);$selectedBinding=[pscustomobject][ordered]@{relativePath=[string]$p.files.performanceReceipt.relativePath;bytes=[long]$p.files.performanceReceipt.bytes;fileSha256=[string]$p.files.performanceReceipt.sha256;canonicalSha256=$selectedCanonical}
    $captureManifest.performanceProtocol.samplesStatus=[string]$selectedValue.aggregateStatus;$captureManifest.performanceProtocol.evidenceReceipt=$selectedBinding
    $captureManifest.performanceProtocol.pipelineCommit=[pscustomobject][ordered]@{relativePath=$commitRelative;bytes=[long]$pipeline.Stable.Bytes;fileSha256=[string]$pipeline.Stable.Sha256;canonicalSha256=[string]$pipeline.CanonicalSha256}
    $manifestTarget=Join-Path $stage 'v0.2-renderer-compatibility-manifest.json';[IO.File]::WriteAllText($manifestTarget,($captureManifest|ConvertTo-Json -Depth 100),(New-Object Text.UTF8Encoding($false)))
    $null=Test-RendererCompatibilityManifest $manifestTarget $stage $repo -ValidateBindings
    foreach($name in $sourceReads.Keys){Assert-RendererStableFileLease $sourceReads[$name].Stable $root $sourceReads[$name].Path "Pipeline $name before final publish"};Assert-RendererStableFileLease $pipeline.Stable $root $commitPath 'Pipeline commit before final publish'
    foreach($lease in $captureLeases){Assert-RendererStableFileLease $lease.Stable $capture $lease.Path 'Capture candidate before final publish'}
    if(Test-Path -LiteralPath $destination){throw 'Final renderer destination appeared concurrently.'};Move-RendererLeasedDirectory $stageLease $stageParent $stage $destination 'Final renderer evidence publish';$stage=$null;$committed=$true
    foreach($name in $sourceReads.Keys){Assert-RendererStableFileLease $sourceReads[$name].Stable $root $sourceReads[$name].Path "Pipeline $name after final publish"};Assert-RendererStableFileLease $pipeline.Stable $root $commitPath 'Pipeline commit after final publish'
    [pscustomobject][ordered]@{EvidenceClassification='PackagedCompatibilityCandidate';ManifestVersion=[int]$captureManifest.manifestVersion;Status='FinalizedManifestCreated';ManifestPath=(Join-Path $destination 'v0.2-renderer-compatibility-manifest.json');OutputDirectory=$destination;PerformanceStatus=[string]$selectedValue.aggregateStatus;ActualHerdrRuntime='NOT_OBSERVED';Release='NOT_OBSERVED';CreditGranted=$false}
}finally{foreach($lease in $captureLeases){if($null-ne$lease.Stable.Stream){$lease.Stable.Stream.Dispose()}};foreach($name in @($sourceReads.Keys)){if($null-ne$sourceReads[$name].Stable.Stream){$sourceReads[$name].Stable.Stream.Dispose()}};if($null-ne$pipeline-and$null-ne$pipeline.Stable.Stream){$pipeline.Stable.Stream.Dispose()};if($null-ne$stage-and(Test-Path -LiteralPath $stage)-and$null-ne$stageLease){Remove-FinalOwnedTree $stageLease (Split-Path -Parent $stage) $stage}elseif($null-ne$stageLease-and$null-ne$stageLease.Handle-and-not$stageLease.Handle.IsClosed){$stageLease.Handle.Dispose()}}
