#requires -Version 5.1
$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
. (Join-Path $PSScriptRoot 'RendererCompatibility.Common.ps1')
$scriptPath=Join-Path $PSScriptRoot 'New-V02MatrixEvidenceReceipt.ps1'
$cases=@(Get-RendererGovernedMatrixCases)
if($cases.Count-ne14){throw "Expected exactly 14 governed automated matrix cases; observed $($cases.Count)."}
$tempBase=Join-Path $env:TEMP "HerdrOps-MatrixTests-$([guid]::NewGuid())"
$repositoryRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$script:FixtureNow=[DateTimeOffset]::UtcNow
$script:FixtureRunStarted=$script:FixtureNow.AddSeconds(-35)
$script:FixtureRunEnded=$script:FixtureNow.AddSeconds(-5)

Add-Type -AssemblyName PresentationCore
function Write-RendererTestPng { param([string]$Path,[int]$Width,[int]$Height);if(Test-Path -LiteralPath $Path){return};$visual=New-Object Windows.Media.DrawingVisual;$drawing=$visual.RenderOpen();try{$drawing.DrawRectangle((New-Object Windows.Media.SolidColorBrush ([Windows.Media.Color]::FromRgb(50,30,20))),$null,(New-Object Windows.Rect(0,0,([double]$Width),([double]$Height))));$drawing.DrawRectangle((New-Object Windows.Media.SolidColorBrush ([Windows.Media.Color]::FromRgb(40,120,220))),$null,(New-Object Windows.Rect(([double]$Width/4),([double]$Height/4),([double]$Width/2),([double]$Height/2))))}finally{$drawing.Close()};$bitmap=New-Object Windows.Media.Imaging.RenderTargetBitmap($Width,$Height,96,96,[Windows.Media.PixelFormats]::Pbgra32);$bitmap.Render($visual);$encoder=New-Object Windows.Media.Imaging.PngBitmapEncoder;$encoder.Frames.Add([Windows.Media.Imaging.BitmapFrame]::Create($bitmap));$stream=[IO.File]::Open($Path,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);try{$encoder.Save($stream)}finally{$stream.Dispose()} }
function Write-RendererBlankPng { param([string]$Path,[int]$Width,[int]$Height);if(Test-Path -LiteralPath $Path){Remove-Item -LiteralPath $Path};$bitmap=New-Object Windows.Media.Imaging.WriteableBitmap($Width,$Height,96,96,[Windows.Media.PixelFormats]::Bgra32,$null);$encoder=New-Object Windows.Media.Imaging.PngBitmapEncoder;$encoder.Frames.Add([Windows.Media.Imaging.BitmapFrame]::Create($bitmap));$stream=[IO.File]::Open($Path,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);try{$encoder.Save($stream)}finally{$stream.Dispose()} }

function Expect-Failure {param([string]$Name,[scriptblock]$Action,[string]$ExpectedSubstring='');$failed=$false;$message='';try{&$Action}catch{$failed=$true;$message=$_.Exception.Message};if(-not$failed){throw "Expected hostile '$Name' to fail."};if($ExpectedSubstring-and$message-notmatch[regex]::Escape($ExpectedSubstring)){throw "Hostile '$Name' reached the wrong guard. Expected '$ExpectedSubstring'; observed '$message'."};Write-Host "PASS negative: $Name"}
function Copy-Map($Map){$copy=@{};foreach($key in $Map.Keys){$copy[$key]=$Map[$key]};return $copy}
function New-RawPayload {
    param([string]$CaseId,[string]$ObservedUtc,[bool]$Passed=$true,[string]$ProvenanceKind='SyntheticFixture',[hashtable]$Overrides=@{},[DateTimeOffset]$RunStarted=$script:FixtureRunStarted,[DateTimeOffset]$RunEnded=$script:FixtureRunEnded,[string]$RunId='fixture-run-0001')
    $contract=Get-RendererMatrixCaseContract $CaseId
    $checks=@($contract.Checks|ForEach-Object{[pscustomobject][ordered]@{name=$_;observedValue=if($Passed){Get-RendererMatrixExpectedCheckValue $_}else{'FAIL'}}})
    $provenance=if($ProvenanceKind-ceq'ActualHerdrRuntime'){
        [pscustomobject][ordered]@{kind='ActualHerdrRuntime';collector='HerdrOpsMatrixRuntimeCollector';actualHerdrObserved=$true;candidate=[pscustomobject][ordered]@{commitSha='0'*40;treeSha='0'*40;packageReceipt=[pscustomobject][ordered]@{relativePath='missing.json';bytes=1;fileSha256='A'*64;canonicalSha256='B'*64}};session=[pscustomobject][ordered]@{kind='LocalConsole';elevated=$false;userScope='SingleUser';processId=1;processStartUtc='2026-08-22T11:59:00.0000000+00:00';executablePath='C:\HerdrOps.App.exe';executableSha256='A'*64};semanticEvent=[pscustomobject][ordered]@{caseId=$CaseId;eventName="matrix-case-observed:$CaseId";observedUtc=$ObservedUtc}}
    }elseif($ProvenanceKind-ceq'AutomatedPackagedRendering'){
        $exeRelative="$($script:CurrentRawDirectory)/collector.exe";$exePath=Join-Path $script:CurrentEvidenceRoot $exeRelative;if(-not(Test-Path $exePath)){[IO.File]::WriteAllText($exePath,'fixture collector',(New-Object Text.UTF8Encoding($false)))};$exeSha=(Get-FileHash $exePath -Algorithm SHA256).Hash;[pscustomobject][ordered]@{kind='AutomatedPackagedRendering';collector='RendererMatrixAutomatedPackagedCollector';actualHerdrObserved=$false;candidate=[pscustomobject][ordered]@{commitSha='2'*40;treeSha='1'*40;packageReceiptCanonicalSha256='A'*64};session=[pscustomobject][ordered]@{sessionId='fixture-session-0001';kind='AutomatedPackaged';elevated=$false;userScope='SingleUser';processId=1234;processStartUtc=$RunStarted.ToString('O');executableRelativePath=$exeRelative;executableSha256=$exeSha};operator=[pscustomobject][ordered]@{identity='@operator';role='EvidenceOperator'};observer=[pscustomobject][ordered]@{identity='@observer';role='IndependentAgentReviewer'}}
    }else{[pscustomobject][ordered]@{kind=$ProvenanceKind;collector=switch($ProvenanceKind){'StaticInspection'{'RendererMatrixStaticInspector'};'ContractHarness'{'RendererMatrixContractHarness'};default{'RendererMatrixSyntheticFixture'}};actualHerdrObserved=$false}}
    $run=[pscustomobject][ordered]@{runId=$RunId;startedUtc=$RunStarted.ToString('O');endedUtc=$RunEnded.ToString('O');sessionId='fixture-session-0001';candidateCommitSha='2'*40;candidateTreeSha='1'*40;packageReceiptCanonicalSha256='A'*64}
    $automated=$ProvenanceKind-ceq'AutomatedPackagedRendering';$artifacts=@();if($automated-and$contract.Kind-ceq'Display'){$dims=$CaseId.Split('-')[0].Split('x');$pngPath="$($script:CurrentRawDirectory)/$CaseId.png";Write-RendererTestPng -Path (Join-Path $script:CurrentRawRoot "$CaseId.png") -Width ([int]$dims[0]) -Height ([int]$dims[1]);$identity=Get-RendererStableFileIdentity $script:CurrentEvidenceRoot (Join-Path $script:CurrentRawRoot "$CaseId.png") 'fixture png';$artifacts=@([pscustomobject][ordered]@{kind='OffscreenPng';relativePath=$pngPath;bytes=[long]$identity.Bytes;sha256=[string]$identity.Sha256;widthPixels=[int]$dims[0];heightPixels=[int]$dims[1]})}
    $payload=[pscustomobject][ordered]@{schemaVersion=if($automated){4}else{3};caseId=$CaseId;observedUtc=$ObservedUtc;run=$run;observation=[pscustomobject][ordered]@{kind=$contract.Kind;target=$CaseId;checks=$checks};provenance=$provenance;details="typed observation for $CaseId"};if($automated){$payload|Add-Member artifacts $artifacts}
    foreach($key in $Overrides.Keys){switch($key){'ObservationKind'{$payload.observation.kind=$Overrides[$key]};'Target'{$payload.observation.target=$Overrides[$key]};'ActualHerdrObserved'{$payload.provenance.actualHerdrObserved=$Overrides[$key]};'Collector'{$payload.provenance.collector=$Overrides[$key]};default{throw "Unknown raw override '$key'."}}}
    return $payload
}
function Write-TestJson($Value,[string]$Path){$parent=[IO.Path]::GetDirectoryName($Path);if(-not[IO.Directory]::Exists($parent)){[IO.Directory]::CreateDirectory($parent)|Out-Null};Write-RendererPackageCanonicalJson -Value $Value -Path $Path -RepositoryRoot $repositoryRoot}
function New-RawSet {
    param([string]$Root,[int]$FailIndex=-1,[int]$OutOfOrderIndex=-1,[string]$ProvenanceKind='SyntheticFixture',[string]$RawDirectory='raw',[Nullable[DateTimeOffset]]$RunEndedUtc=$null,[string]$RunId='fixture-run-0001')
    $runEnded=if($null-ne$RunEndedUtc){[DateTimeOffset]$RunEndedUtc}else{$script:FixtureRunEnded};$runStarted=$runEnded.AddSeconds(-35)
    New-Item -ItemType Directory -Path (Join-Path $Root $RawDirectory) -Force|Out-Null;$script:CurrentEvidenceRoot=$Root;$script:CurrentRawDirectory=$RawDirectory;$script:CurrentRawRoot=Join-Path $Root $RawDirectory;$paths=@{};$outcomes=@{}
    for($i=0;$i-lt$cases.Count;$i++){$case=$cases[$i];$paths[$case]="$RawDirectory/$case.json";$outcomes[$case]='PASS';$second=if($i-eq$OutOfOrderIndex){0}else{$i};$utc=$runStarted.AddSeconds($second+1).ToString('O');Write-TestJson (New-RawPayload $case $utc ($i-ne$FailIndex) $ProvenanceKind @{} $runStarted $runEnded $RunId) (Join-Path $Root $paths[$case])}
    return [pscustomobject]@{Paths=$paths;Outcomes=$outcomes}
}
function New-Common([string]$Root,$Set){return @{OperatorIdentity='@operator';OperatorRole='EvidenceOperator';ObserverIdentity='@observer';ObserverRole='IndependentAgentReviewer';EvidenceBoundary='Synthetic';Outcomes=$Set.Outcomes;RawEvidencePaths=$Set.Paths;EvidenceRoot=$Root;RepositoryRoot=$repositoryRoot}}
function Start-ProducerChild {
    param([string]$Root,[string]$Destination,[int]$PauseMilliseconds,[int]$RecoveryPauseMilliseconds=0,[int]$CleanupPauseMilliseconds=0,[int]$PublicationPauseMilliseconds=0,[int]$FailureCount=0,[string]$RawDirectory='raw')
    $runner=Join-Path $Root ('runner-'+[guid]::NewGuid().ToString('N')+'.ps1');$errorPath=$runner+'.error'
    $source=@'
param([string]$Producer,[string]$Root,[string]$Destination,[string]$Repository,[int]$Pause,[int]$RecoveryPause,[int]$CleanupPause,[int]$PublicationPause,[int]$FailureCount,[string]$RawDirectory,[string]$ErrorPath)
$ErrorActionPreference='Stop'
. (Join-Path (Split-Path $Producer) 'RendererCompatibility.Common.ps1')
$raw=@{};$outcomes=@{};foreach($case in @(Get-RendererGovernedMatrixCases)){$raw[$case]="$RawDirectory/$case.json";$outcomes[$case]='PASS'}
try{$null=& $Producer -DestinationPath $Destination -OperatorIdentity '@child-op' -OperatorRole EvidenceOperator -ObserverIdentity '@child-observer' -ObserverRole IndependentAgentReviewer -EvidenceBoundary Synthetic -Outcomes $outcomes -RawEvidencePaths $raw -EvidenceRoot $Root -RepositoryRoot $Repository -PauseAfterStagingReadyMilliseconds $Pause -PauseAfterRecoveryIdentityVerifiedMilliseconds $RecoveryPause -PauseAfterCleanupIdentityVerifiedMilliseconds $CleanupPause -PauseAfterPublicationIdentityVerifiedMilliseconds $PublicationPause -SimulateFailureAfterReceiptCount $FailureCount}catch{[IO.File]::WriteAllText($ErrorPath,$_.Exception.Message,(New-Object Text.UTF8Encoding($false)));exit 1}
'@
    [IO.File]::WriteAllText($runner,$source,(New-Object Text.UTF8Encoding($false)))
    $engine=(Get-Process -Id $PID).Path;$psi=New-Object Diagnostics.ProcessStartInfo;$psi.FileName=$engine;$psi.Arguments="-NoLogo -NoProfile -ExecutionPolicy Bypass -File `"$runner`" -Producer `"$scriptPath`" -Root `"$Root`" -Destination `"$Destination`" -Repository `"$repositoryRoot`" -Pause $PauseMilliseconds -RecoveryPause $RecoveryPauseMilliseconds -CleanupPause $CleanupPauseMilliseconds -PublicationPause $PublicationPauseMilliseconds -FailureCount $FailureCount -RawDirectory `"$RawDirectory`" -ErrorPath `"$errorPath`"";$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true
    $process=[Diagnostics.Process]::Start($psi);$process|Add-Member -NotePropertyName ErrorPath -NotePropertyValue $errorPath;return $process
}
function Wait-Staging([string]$Root,[int]$TimeoutSeconds=15){$limit=[DateTime]::UtcNow.AddSeconds($TimeoutSeconds);do{$found=@(Get-ChildItem -LiteralPath $Root -Directory -Filter '.matrix-receipts-staging-*' -ErrorAction SilentlyContinue|Where-Object{Test-Path -LiteralPath (Join-Path $_.FullName '.owner.json')});if($found.Count){return $found[0].FullName};Start-Sleep -Milliseconds 100}while([DateTime]::UtcNow-lt$limit);throw 'Timed out waiting for owned staging marker.'}
function Wait-Marker([string]$Path,[int]$TimeoutSeconds=15){$limit=[DateTime]::UtcNow.AddSeconds($TimeoutSeconds);while(-not(Test-Path -LiteralPath $Path)-and[DateTime]::UtcNow-lt$limit){Start-Sleep -Milliseconds 100};if(-not(Test-Path -LiteralPath $Path)){throw "Timed out waiting for '$Path'."}}

try{
    New-Item -ItemType Directory -Path $tempBase|Out-Null
    $root=Join-Path $tempBase 'positive';New-Item -ItemType Directory -Path $root|Out-Null;$set=New-RawSet $root;$common=New-Common $root $set;$destination=Join-Path $root 'receipts';$files=@(&$scriptPath -DestinationPath $destination @common)
    if($files.Count-ne14){throw 'Expected exactly 14 published receipts.'};for($i=0;$i-lt14;$i++){$receipt=Get-Content -LiteralPath $files[$i] -Raw|ConvertFrom-Json;if($receipt.caseId-cne$cases[$i]-or$receipt.outcome-cne'PASS'-or$receipt.evidenceBoundary.evidenceClass-cne'Synthetic'-or$receipt.evidenceBoundary.release-cne'NOT_OBSERVED'-or[bool]$receipt.evidenceBoundary.creditGranted){throw 'Receipt authority/order mismatch.'}}
    Write-Host 'PASS positive: exact typed governed 14-set derives PASS/Synthetic and preserves no-credit'

    $autoRoot=Join-Path $tempBase 'auto';New-Item -ItemType Directory -Path $autoRoot|Out-Null;$autoSet=New-RawSet $autoRoot;$auto=@{OperatorIdentity='@op';OperatorRole='EvidenceOperator';ObserverIdentity='@obs';ObserverRole='IndependentAgentReviewer';RawEvidencePaths=$autoSet.Paths;EvidenceRoot=$autoRoot;RepositoryRoot=$repositoryRoot};$null=&$scriptPath -DestinationPath (Join-Path $autoRoot 'receipts') @auto;Write-Host 'PASS positive: outcome and evidence class are independently derived without caller assertions'

    $automatedRoot=Join-Path $tempBase 'automated';New-Item -ItemType Directory -Path $automatedRoot|Out-Null;$automatedSet=New-RawSet $automatedRoot -1 -1 'AutomatedPackagedRendering';$automatedCommon=New-Common $automatedRoot $automatedSet;$automatedCommon.EvidenceBoundary='AutomatedPackagedRendering';$automatedFiles=@(&$scriptPath -DestinationPath (Join-Path $automatedRoot 'receipts') @automatedCommon);foreach($file in $automatedFiles){$receipt=Get-Content -LiteralPath $file -Raw|ConvertFrom-Json;if($receipt.evidenceBoundary.evidenceClass-cne'AutomatedPackagedRendering'-or$receipt.operator.identity-cne'@operator'-or$receipt.observer.identity-cne'@observer'){throw 'Automated packaged rendering receipt lost its governed provenance.'}};Write-Host 'PASS positive: automated packaged rendering binds exact candidate/package/session and distinct Agent roles'
    $pixelRoot=Join-Path $tempBase 'pixel-tamper';New-Item -ItemType Directory -Path $pixelRoot|Out-Null;$pixelSet=New-RawSet $pixelRoot -1 -1 'AutomatedPackagedRendering';[IO.File]::AppendAllText((Join-Path $pixelRoot 'raw/1920x1080-100.png'),'tamper');$pixelCommon=New-Common $pixelRoot $pixelSet;$pixelCommon.EvidenceBoundary='AutomatedPackagedRendering';Expect-Failure 'bound off-screen pixel artifact tamper' {&$scriptPath -DestinationPath (Join-Path $pixelRoot 'receipts') @pixelCommon} 'byte/hash binding failed'
    $blankRoot=Join-Path $tempBase 'pixel-blank';New-Item -ItemType Directory -Path $blankRoot|Out-Null;$blankSet=New-RawSet $blankRoot -1 -1 'AutomatedPackagedRendering';$blankPng=Join-Path $blankRoot 'raw/1920x1080-100.png';Write-RendererBlankPng $blankPng 1920 1080;$blankRawPath=Join-Path $blankRoot $blankSet.Paths['1920x1080-100'];$blankJson=Get-Content -LiteralPath $blankRawPath -Raw;$blankRaw=ConvertFrom-StrictHumanDesignReviewJson -Json $blankJson -Description 'blank hostile raw';if($PSVersionTable.PSVersion.Major-ge7-and(Get-Command ConvertFrom-Json).Parameters.ContainsKey('DateKind')){$blankRaw=$blankJson|ConvertFrom-Json -DateKind String};$blankIdentity=Get-RendererStableFileIdentity $blankRoot $blankPng 'blank hostile png';$blankRaw.artifacts[0].bytes=[long]$blankIdentity.Bytes;$blankRaw.artifacts[0].sha256=[string]$blankIdentity.Sha256;Write-TestJson $blankRaw $blankRawPath;$blankCommon=New-Common $blankRoot $blankSet;$blankCommon.EvidenceBoundary='AutomatedPackagedRendering';Expect-Failure 'bound blank off-screen pixel artifact' {&$scriptPath -DestinationPath (Join-Path $blankRoot 'receipts') @blankCommon} 'blank, transparent, uniform, or lacks bounded rendered content'

    Expect-Failure 'pre-existing destination no-clobber' {&$scriptPath -DestinationPath $destination @common} 'already exists; receipt publication is no-clobber'
    $crashRoot=Join-Path $tempBase 'rollback';New-Item -ItemType Directory -Path $crashRoot|Out-Null;$crashSet=New-RawSet $crashRoot;$crashCommon=New-Common $crashRoot $crashSet;Expect-Failure 'caught pre-publication crash rollback' {&$scriptPath -DestinationPath (Join-Path $crashRoot 'receipts') @crashCommon -SimulateFailureAfterReceiptCount 12} 'Simulated pre-publication interruption';if(@(Get-ChildItem $crashRoot -Directory -Filter '.matrix-receipts-staging-*').Count){throw 'Caught crash left staging.'}

    $failRoot=Join-Path $tempBase 'derived-fail';New-Item -ItemType Directory -Path $failRoot|Out-Null;$failSet=New-RawSet $failRoot 0;$failCommon=New-Common $failRoot $failSet;Expect-Failure 'caller PASS rejected against independently derived failed check' {&$scriptPath -DestinationPath (Join-Path $failRoot 'receipts') @failCommon} 'Synchronized forged PASS detected'
    $typedRoot=Join-Path $tempBase 'typed';New-Item -ItemType Directory -Path $typedRoot|Out-Null;$typedSet=New-RawSet $typedRoot;$first=$cases[0];Write-TestJson (New-RawPayload $first $script:FixtureRunStarted.AddSeconds(1).ToString('O') $true 'SyntheticFixture' @{ObservationKind='Accessibility'}) (Join-Path $typedRoot $typedSet.Paths[$first]);$typedCommon=New-Common $typedRoot $typedSet;Expect-Failure 'case-specific observation type mismatch' {&$scriptPath -DestinationPath (Join-Path $typedRoot 'receipts') @typedCommon} 'type/target does not match'

    $runtimeRoot=Join-Path $tempBase 'runtime';New-Item -ItemType Directory -Path $runtimeRoot|Out-Null;$runtimeSet=New-RawSet $runtimeRoot -1 -1 'ActualHerdrRuntime';$runtimeCommon=New-Common $runtimeRoot $runtimeSet;Expect-Failure 'self-authored Runtime lacks exact clean candidate and live Herdr provenance' {&$scriptPath -DestinationPath (Join-Path $runtimeRoot 'receipts') @runtimeCommon} 'claims unearned Runtime'

    foreach($index in @(1,2)){$chronRoot=Join-Path $tempBase "chronology-$index";New-Item -ItemType Directory -Path $chronRoot|Out-Null;$chronSet=New-RawSet $chronRoot -1 $index;$chronCommon=New-Common $chronRoot $chronSet;Expect-Failure "strict monotonic unique chronology $index" {&$scriptPath -DestinationPath (Join-Path $chronRoot 'receipts') @chronCommon} 'strictly increasing and unique'}
    $staleRoot=Join-Path $tempBase 'stale-replay';New-Item -ItemType Directory -Path $staleRoot|Out-Null;$staleSet=New-RawSet $staleRoot;$staleStarted=[DateTimeOffset]::UtcNow.AddMinutes(-11);$staleEnded=[DateTimeOffset]::UtcNow.AddMinutes(-10);for($i=0;$i-lt$cases.Count;$i++){$case=$cases[$i];$path=Join-Path $staleRoot $staleSet.Paths[$case];$json=Get-Content $path -Raw;$payload=ConvertFrom-StrictHumanDesignReviewJson -Json $json -Description 'stale fixture';if($PSVersionTable.PSVersion.Major-ge7){$payload=$json|ConvertFrom-Json -DateKind String};$payload.run.startedUtc=$staleStarted.ToString('O');$payload.run.endedUtc=$staleEnded.ToString('O');$payload.observedUtc=$staleStarted.AddSeconds($i+1).ToString('O');Write-TestJson $payload $path};$staleCommon=New-Common $staleRoot $staleSet;Expect-Failure 'stale raw run replay cannot supply a caller-controlled freshness anchor' {&$scriptPath -DestinationPath (Join-Path $staleRoot 'receipts') @staleCommon} 'trusted current five-minute publication window'
    $mixedRunRoot=Join-Path $tempBase 'mixed-run';New-Item -ItemType Directory -Path $mixedRunRoot|Out-Null;$mixedRunSet=New-RawSet $mixedRunRoot;$mixedPath=Join-Path $mixedRunRoot $mixedRunSet.Paths[$cases[1]];$mixedJson=Get-Content $mixedPath -Raw;$mixedPayload=ConvertFrom-StrictHumanDesignReviewJson -Json $mixedJson -Description 'mixed run fixture';if($PSVersionTable.PSVersion.Major-ge7){$mixedPayload=$mixedJson|ConvertFrom-Json -DateKind String};$mixedPayload.run.runId='fixture-run-0002';Write-TestJson $mixedPayload $mixedPath;$mixedCommon=New-Common $mixedRunRoot $mixedRunSet;Expect-Failure 'mixed run/session identity across governed cases' {&$scriptPath -DestinationPath (Join-Path $mixedRunRoot 'receipts') @mixedCommon} 'exact common run/session/candidate/package identity'
    $identity=Copy-Map $common;$identity.ObserverIdentity='@OPERATOR';Expect-Failure 'case-insensitive operator observer identity collision' {&$scriptPath -DestinationPath (Join-Path $root 'identity') @identity} 'must be distinct'
    $missing=Copy-Map $set.Paths;$missing.Remove($cases[0]);$hostile=Copy-Map $common;$hostile.RawEvidencePaths=$missing;Expect-Failure 'missing governed case' {&$scriptPath -DestinationPath (Join-Path $root 'missing') @hostile} 'exactly the 14 governed case IDs'

    $hardRoot=Join-Path $tempBase 'hardlink';New-Item -ItemType Directory -Path $hardRoot|Out-Null;$hardSet=New-RawSet $hardRoot;$secondPath=Join-Path $hardRoot $hardSet.Paths[$cases[1]];Remove-Item -LiteralPath $secondPath;New-Item -ItemType HardLink -Path $secondPath -Target (Join-Path $hardRoot $hardSet.Paths[$cases[0]])|Out-Null;$hardCommon=New-Common $hardRoot $hardSet;Expect-Failure 'single hardlinked raw leaf' {&$scriptPath -DestinationPath (Join-Path $hardRoot 'receipts') @hardCommon} 'must have exactly one hard link';Remove-Item -LiteralPath $hardRoot -Recurse -Force;if(Test-Path -LiteralPath $hardRoot){throw 'Rejected hardlinked raw leaf retained an open handle.'};Write-Host 'PASS negative: rejected hardlinked raw leaf releases its pre-transfer handle for deterministic cleanup'

    $linkRoot=Join-Path $root 'link-hostile';New-Item -ItemType Directory -Path $linkRoot|Out-Null;$junction=Join-Path $linkRoot 'raw-link';New-Item -ItemType Junction -Path $junction -Target (Join-Path $root 'raw')|Out-Null;$bad=Copy-Map $set.Paths;$bad[$cases[0]]='link-hostile/raw-link/'+$cases[0]+'.json';$hostile=Copy-Map $common;$hostile.RawEvidencePaths=$bad;Expect-Failure 'raw junction reaches reparse guard' {&$scriptPath -DestinationPath (Join-Path $root 'junction-receipts') @hostile} 'contains a reparse point'

    $childRoot=Join-Path $tempBase 'real-child';New-Item -ItemType Directory -Path $childRoot|Out-Null;$childSet=New-RawSet $childRoot;$childCommon=New-Common $childRoot $childSet;$childDest=Join-Path $childRoot 'receipts';$child=Start-ProducerChild $childRoot $childDest 120000;$orphan=Wait-Staging $childRoot;$child.Kill();$child.WaitForExit();Start-Sleep -Seconds 3;$null=&$scriptPath -DestinationPath $childDest @childCommon;if(Test-Path -LiteralPath $orphan){throw 'Dead child staging was not recovered.'};Write-Host 'PASS positive: real killed child recovered only after PID/start-time/age/marker/identity validation'

    $recoveryRoot=Join-Path $tempBase 'recovery-swap';New-Item -ItemType Directory -Path $recoveryRoot|Out-Null;$null=New-RawSet $recoveryRoot;$recoveryDest=Join-Path $recoveryRoot 'receipts';$dead=Start-ProducerChild $recoveryRoot $recoveryDest 120000;$recoveryOrphan=Wait-Staging $recoveryRoot;$dead.Kill();$dead.WaitForExit();Start-Sleep -Seconds 3;$recoverer=Start-ProducerChild $recoveryRoot $recoveryDest 0 3000;$ready=Join-Path $recoveryRoot '.recovery-identity-verified';Wait-Marker $ready;$recoverySwapBlocked=$false;try{Move-Item -LiteralPath $recoveryOrphan -Destination ($recoveryOrphan+'-replacement-attempt') -ErrorAction Stop}catch{$recoverySwapBlocked=$true};if(-not$recoverySwapBlocked){throw 'Recovery directory rename was not blocked after exact held identity verification.'};$recoverer.WaitForExit();$recoverError=if(Test-Path $recoverer.ErrorPath){Get-Content $recoverer.ErrorPath -Raw}else{''};if($recoverer.ExitCode-ne0){throw "Held-handle recovery failed unexpectedly: $recoverError"};if(Test-Path $recoveryOrphan){throw 'Held-handle recovery left the owned orphan.'};Write-Host 'PASS negative: recovery rename is blocked after identity verification and deletion uses the held handle'

    $cleanupRoot=Join-Path $tempBase 'cleanup-swap';New-Item -ItemType Directory -Path $cleanupRoot|Out-Null;$null=New-RawSet $cleanupRoot;$cleanupDest=Join-Path $cleanupRoot 'receipts';$cleanupChild=Start-ProducerChild $cleanupRoot $cleanupDest 0 0 3000 0 12;$cleanupStage=Wait-Staging $cleanupRoot;Wait-Marker (Join-Path $cleanupRoot '.cleanup-identity-verified');$cleanupSwapBlocked=$false;try{Move-Item -LiteralPath $cleanupStage -Destination ($cleanupStage+'-replacement-attempt') -ErrorAction Stop}catch{$cleanupSwapBlocked=$true};if(-not$cleanupSwapBlocked){throw 'Failed-transaction staging rename was not blocked after cleanup identity verification.'};$cleanupChild.WaitForExit();$cleanupError=if(Test-Path $cleanupChild.ErrorPath){Get-Content $cleanupChild.ErrorPath -Raw}else{''};if($cleanupChild.ExitCode-eq0-or$cleanupError-notmatch'Simulated pre-publication interruption'){throw "Failed cleanup hostile reached the wrong guard: $cleanupError"};if((Test-Path $cleanupStage)-or(Test-Path $cleanupDest)){throw 'Failed held-handle cleanup left staging or published a destination.'};Write-Host 'PASS negative: failure cleanup blocks rename after identity verification and deletes only the held staging directory'

    $conRoot=Join-Path $tempBase 'concurrent';New-Item -ItemType Directory -Path $conRoot|Out-Null;$null=New-RawSet $conRoot;$conSet=New-RawSet $conRoot -RawDirectory 'raw-main' -RunId 'fixture-run-main';$conCommon=New-Common $conRoot $conSet;$conDest=Join-Path $conRoot 'receipts';$loser=Start-ProducerChild $conRoot $conDest 3000;$null=Wait-Staging $conRoot;$null=&$scriptPath -DestinationPath $conDest @conCommon;$loser.WaitForExit();$loserError=if(Test-Path $loser.ErrorPath){Get-Content $loser.ErrorPath -Raw}else{''};if($loser.ExitCode-eq0-or$loserError-notmatch'atomic no-clobber'){throw "Concurrent producer reached the wrong guard: $loserError"};Write-Host 'PASS negative: distinct tuples still reach atomic destination no-clobber and select one winner'

    $replayRoot=Join-Path $tempBase 'replay-two-destinations';New-Item -ItemType Directory -Path $replayRoot|Out-Null;$replaySet=New-RawSet $replayRoot;$replayCommon=New-Common $replayRoot $replaySet;$replayA=Join-Path $replayRoot 'receipts-a';$replayB=Join-Path $replayRoot 'receipts-b';$null=&$scriptPath -DestinationPath $replayA @replayCommon;$registry=Join-Path $replayRoot '.matrix-receipt-replay-registry';$entry=@(Get-ChildItem -LiteralPath $registry -Directory -Filter '.publication-*');if($entry.Count-ne1){throw 'Expected exactly one replay registry publication entry.'};Set-Content -LiteralPath (Join-Path $entry[0].FullName 'canary.txt') -Value 'preserve';Expect-Failure 'identical tuple cannot publish to a second destination' {&$scriptPath -DestinationPath $replayB @replayCommon} 'Replay registry already contains exact matrix publication tuple';if(-not(Test-Path -LiteralPath (Join-Path $entry[0].FullName 'canary.txt'))-or(Test-Path -LiteralPath $replayB)){throw 'Sequential replay mutated the ledger canary or published a second destination.'};Write-Host 'PASS negative: exact tuple replay is globally rejected within the fixed evidence-root registry and preserves its canary'

    $raceRoot=Join-Path $tempBase 'replay-concurrent-destinations';New-Item -ItemType Directory -Path $raceRoot|Out-Null;$null=New-RawSet $raceRoot;New-Item -ItemType Directory -Path (Join-Path $raceRoot 'protected')|Out-Null;Set-Content -LiteralPath (Join-Path $raceRoot 'protected/canary.txt') -Value 'preserve';$raceA=Start-ProducerChild $raceRoot (Join-Path $raceRoot 'receipts-a') 3000;$raceB=Start-ProducerChild $raceRoot (Join-Path $raceRoot 'receipts-b') 3000;$raceA.WaitForExit();$raceB.WaitForExit();$raceErrors=@($raceA,$raceB|ForEach-Object{if(Test-Path $_.ErrorPath){Get-Content $_.ErrorPath -Raw}else{''}});$raceSuccesses=@($raceA,$raceB|Where-Object{$_.ExitCode-eq0});$raceFailures=@($raceA,$raceB|Where-Object{$_.ExitCode-ne0});$publishedDestinations=@('receipts-a','receipts-b'|Where-Object{Test-Path -LiteralPath (Join-Path $raceRoot $_)});if($raceSuccesses.Count-ne1-or$raceFailures.Count-ne1-or$publishedDestinations.Count-ne1-or(@($raceErrors|Where-Object{$_-match'Replay registry already contains exact matrix publication tuple'}).Count-ne1)){throw "Concurrent tuple replay did not select exactly one registry winner: $($raceErrors-join' | ')"};if(-not(Test-Path -LiteralPath (Join-Path $raceRoot 'protected/canary.txt'))){throw 'Concurrent replay mutated the protected canary.'};Write-Host 'PASS negative: concurrent identical tuple publications to different destinations select one atomic registry winner and preserve canary'

    $boundaryRoot=Join-Path $tempBase 'freshness-commit-boundary';New-Item -ItemType Directory -Path $boundaryRoot|Out-Null;$boundarySet=New-RawSet $boundaryRoot -RunEndedUtc ([DateTimeOffset]::UtcNow.AddSeconds(-298));$boundaryCommon=New-Common $boundaryRoot $boundarySet;New-Item -ItemType Directory -Path (Join-Path $boundaryRoot 'protected')|Out-Null;Set-Content -LiteralPath (Join-Path $boundaryRoot 'protected/canary.txt') -Value 'preserve';$boundaryDestination=Join-Path $boundaryRoot 'receipts';Expect-Failure 'run ages beyond five minutes before atomic publication commit' {&$scriptPath -DestinationPath $boundaryDestination @boundaryCommon -PauseAfterStagingReadyMilliseconds 6000} 'trusted current five-minute publication commit window';$boundaryEntries=@(Get-ChildItem -LiteralPath (Join-Path $boundaryRoot '.matrix-receipt-replay-registry') -Directory -Filter '.publication-*');if($boundaryEntries.Count-ne0-or(Test-Path -LiteralPath $boundaryDestination)-or-not(Test-Path -LiteralPath (Join-Path $boundaryRoot 'protected/canary.txt'))){throw 'Freshness commit failure did not roll back its exact replay claim or preserve the canary.'};Write-Host 'PASS negative: final trusted-clock boundary rejects older-than-300-second publication and rolls back only its held replay claim'

    $leafRoot=Join-Path $tempBase 'leaf-replacement';New-Item -ItemType Directory -Path $leafRoot|Out-Null;$leafSet=New-RawSet $leafRoot;$leafDest=Join-Path $leafRoot 'receipts';$leafPath=Join-Path $leafRoot $leafSet.Paths[$cases[0]];$replacement=$leafPath+'.replacement';Copy-Item -LiteralPath $leafPath -Destination $replacement;$leafChild=Start-ProducerChild $leafRoot $leafDest 3000;$null=Wait-Staging $leafRoot;$replaceBlocked=$false;try{[IO.File]::Replace($replacement,$leafPath,$null)}catch{$replaceBlocked=$true};if(-not$replaceBlocked){throw 'Byte-identical raw leaf replacement was not blocked by the held raw handle.'};$leafChild.WaitForExit();if($leafChild.ExitCode-ne0){$leafError=if(Test-Path $leafChild.ErrorPath){Get-Content $leafChild.ErrorPath -Raw}else{''};throw "Held raw identity producer failed unexpectedly: $leafError"};if(Test-Path $replacement){Remove-Item $replacement};Write-Host 'PASS negative: byte-identical raw leaf replacement is blocked while the original FileId handle is held'

    $swapRoot=Join-Path $tempBase 'staging-swap';New-Item -ItemType Directory -Path $swapRoot|Out-Null;$null=New-RawSet $swapRoot;$swapDest=Join-Path $swapRoot 'receipts';$swapChild=Start-ProducerChild $swapRoot $swapDest 0 0 0 3000;$stage=Wait-Staging $swapRoot;Wait-Marker (Join-Path $swapRoot '.publication-identity-verified');$publicationSwapBlocked=$false;try{Move-Item -LiteralPath $stage -Destination ($stage+'-replacement-attempt') -ErrorAction Stop}catch{$publicationSwapBlocked=$true};if(-not$publicationSwapBlocked){throw 'Staging rename was not blocked after publication identity verification.'};$swapChild.WaitForExit();$swapError=if(Test-Path $swapChild.ErrorPath){Get-Content $swapChild.ErrorPath -Raw}else{''};if($swapChild.ExitCode-ne0-or-not(Test-Path $swapDest)){throw "Held-handle publication failed unexpectedly: $swapError"};Write-Host 'PASS negative: staging rename is blocked after verification and held-handle publication retains the exact FileId'

    $collisionRoot=Join-Path $tempBase 'publication-collision';New-Item -ItemType Directory -Path $collisionRoot|Out-Null;$null=New-RawSet $collisionRoot;$collisionDest=Join-Path $collisionRoot 'receipts';$collisionChild=Start-ProducerChild $collisionRoot $collisionDest 0 0 0 3000;$collisionStage=Wait-Staging $collisionRoot;Wait-Marker (Join-Path $collisionRoot '.publication-identity-verified');New-Item -ItemType Directory -Path $collisionDest|Out-Null;Set-Content -LiteralPath (Join-Path $collisionDest 'canary.txt') -Value 'preserve';$collisionChild.WaitForExit();$collisionError=if(Test-Path $collisionChild.ErrorPath){Get-Content $collisionChild.ErrorPath -Raw}else{''};if($collisionChild.ExitCode-eq0-or$collisionError-notmatch'atomic no-clobber'){throw "Exact-window destination collision reached the wrong guard: $collisionError"};if(-not(Test-Path (Join-Path $collisionDest 'canary.txt'))-or(Test-Path $collisionStage)){throw 'Exact-window no-clobber mutated the destination replacement or left owned staging.'};Write-Host 'PASS negative: exact post-verification destination collision preserves replacement and cleans only held staging'

    Write-Host "All matrix receipt security tests passed for PowerShell $($PSVersionTable.PSVersion)."
}finally{if(Test-Path -LiteralPath $tempBase){Remove-Item -LiteralPath $tempBase -Recurse -Force}}
