#requires -Version 5.1
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repoSource=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$rendererRoot=Join-Path $repoSource 'tools\v0.2-renderer-compatibility'
. (Join-Path $rendererRoot 'RendererCompatibility.Common.ps1');. (Join-Path $repoSource 'tools\packaging\v0.2\V02PackageIdentity.Common.ps1')
$composer=Join-Path $PSScriptRoot 'Publish-V02Issue10PerformanceSoakEvidence.ps1';$temp=Join-Path ([IO.Path]::GetTempPath()) ('herdrops-i10-compose-'+[Guid]::NewGuid().ToString('N'));$passed=0;$negative=0
function Pass([string]$Name){$script:passed++;Write-Host "PASS positive: $Name"}
function Reject([string]$Name,[scriptblock]$Action,[string]$Pattern=''){$threw=$false;try{&$Action|Out-Null}catch{$threw=$true;if($Pattern-and$_.Exception.Message-notmatch$Pattern){throw "Expected $Pattern, got $($_.Exception.Message)"}};if(-not$threw){throw "Expected rejection: $Name"};$script:negative++;Write-Host "PASS negative: $Name"}
function Clone($Value){ConvertFrom-V02StrictJsonText (($Value|ConvertTo-Json -Depth 100 -Compress)) 'composer clone'}
function Convert-DateValuesToStrings($Value){if($Value-is[DateTime]){return $Value.ToUniversalTime().ToString('O')};if($Value-is[Collections.IDictionary]){$copy=[ordered]@{};foreach($key in $Value.Keys){$copy[$key]=Convert-DateValuesToStrings $Value[$key]};return [pscustomobject]$copy};if($Value-is[pscustomobject]){$copy=[ordered]@{};foreach($property in $Value.PSObject.Properties){$copy[$property.Name]=Convert-DateValuesToStrings $property.Value};return [pscustomobject]$copy};if($Value-is[Collections.IEnumerable]-and$Value-isnot[string]){return ,@($Value|ForEach-Object{Convert-DateValuesToStrings $_})};return $Value}
try{
 $repo=Join-Path $temp 'repo';$evidence=Join-Path $temp 'evidence';$package=Join-Path $evidence 'candidate\package';New-Item -ItemType Directory -Path $package -Force|Out-Null
 foreach($relative in @('Plan\reference-hosts\v0.2.json','Plan\reference-hosts\reference-host-profile.schema.json','tools\lib\V02ReferenceHostProfile.ps1','tools\lib\V02RuntimePackageBinding.ps1','tools\packaging\Packaging.Common.ps1','tools\packaging\v0.2\V02PackageIdentity.Common.ps1','tools\packaging\v0.2\Test-V02PackageIdentity.ps1','tools\packaging\v0.2\package-identity-profile.json','tools\packaging\v0.2\package-identity-receipt.schema.json')){$target=Join-Path $repo $relative;New-Item -ItemType Directory -Path (Split-Path -Parent $target) -Force|Out-Null;Copy-Item -LiteralPath (Join-Path $repoSource $relative) -Destination $target}
 & git -C $repo init --quiet;& git -C $repo -c user.name=HerdrOps-Test -c user.email=test@example.invalid add --all;& git -C $repo -c user.name=HerdrOps-Test -c user.email=test@example.invalid commit --quiet -m fixture;if($LASTEXITCODE){throw 'Composer fixture git creation failed.'};$global:LASTEXITCODE=0
 $commit=(&git -C $repo rev-parse HEAD).Trim();$tree=(&git -C $repo rev-parse 'HEAD^{tree}').Trim();$profilePath=Join-Path $repo 'tools\packaging\v0.2\package-identity-profile.json';$profile=Read-V02PackageIdentityProfile $profilePath
 [IO.File]::WriteAllBytes((Join-Path $package 'HerdrOps.App.exe'),[byte[]](1..32));[IO.File]::WriteAllBytes((Join-Path $package 'HerdrOps.Core.exe'),[byte[]](33..64));$manifest=New-V02PackageManifestObject $profile $repo $package;$manifestPath=Join-Path $package 'package-manifest.json';Write-V02CanonicalJsonFile $manifest $manifestPath $repo
 $archive=Join-Path $evidence 'candidate\HerdrOps-0.2.0-win-x64.zip';$null=New-DeterministicPackageArchive $package $archive;$archiveStable=Get-V02StableFileIdentity $archive;$manifestStable=Get-V02StableFileIdentity $manifestPath;$inventory=Get-V02PackageRootInventory $package -ExcludeRelativePath @('package-manifest.json');$app=@($inventory.Entries|? Path -CEQ 'HerdrOps.App.exe')[0];$core=@($inventory.Entries|? Path -CEQ 'HerdrOps.Core.exe')[0];$profileId=Get-V02PreparationProfileIdentity $profilePath $profile $repo
 $identity=[pscustomobject][ordered]@{schemaVersion=1;profileId=$profile.profileId;issue=149;packageVersion='0.2.0';runtimeIdentifier='win-x64';source=[pscustomobject][ordered]@{commitSha=$commit;treeSha=$tree};profile=[pscustomobject][ordered]@{id=$profileId.Id;relativePath=$profileId.RelativePath;bytes=[long]$profileId.Bytes;fileSha256=$profileId.FileSha256;canonicalSha256=$profileId.CanonicalSha256};archive=[pscustomobject][ordered]@{relativePath=$profile.archiveFileName;fileName=$profile.archiveFileName;bytes=[long]$archiveStable.Length;sha256=$archiveStable.Sha256};packageManifest=[pscustomobject][ordered]@{fileName='package-manifest.json';bytes=[long]$manifestStable.Length;sha256=$manifestStable.Sha256;contentSha256=$manifest.contentSha256;fileCount=[int]$manifest.fileCount;totalBytes=[long]$manifest.totalBytes};components=[pscustomobject][ordered]@{app=[pscustomobject][ordered]@{relativePath='HerdrOps.App.exe';bytes=[long]$app.Length;sha256=$app.Sha256};core=[pscustomobject][ordered]@{relativePath='HerdrOps.Core.exe';bytes=[long]$core.Length;sha256=$core.Sha256}};referenceHost=[pscustomobject][ordered]@{profileId=$profile.referenceHost.profileId;profileSha256=$profile.referenceHost.profileSha256};renderer=[pscustomobject][ordered]@{policy=$profile.renderer.policy;wpfProcessRenderMode=$profile.renderer.wpfProcessRenderMode};evidenceBoundary=[pscustomobject][ordered]@{evidenceClass='PackagedCompatibilityPreparation';runtimeUse='not-used';actualHerdrUsed=$false;runtimeCredit='NOT CLAIMED';releaseCredit='NOT CLAIMED'}}
 $identityPath=Join-Path $evidence 'candidate\identity.json';Write-V02CanonicalJsonFile $identity $identityPath $repo;$identityCanonical=(Read-V02CanonicalIdentityReceipt $identityPath $repo).ReceiptSha256;$runNonce=[Guid]::NewGuid().ToString('N');$acPath=Join-Path $evidence 'ac.json';$batteryPath=Join-Path $evidence 'battery.json'
 foreach($spec in @(@('AC',$acPath),@('Battery',$batteryPath))){$power=$spec[0];$provider={ $power }.GetNewClosure();& (Join-Path $rendererRoot 'Invoke-V02SoakMeasurement.ps1') -Synthetic -PowerSource $power -DestinationPath $spec[1] -EvidenceRoot $evidence -RepositoryRoot $repo -ExpectedSourceCommit $commit -ExpectedSourceTree $tree -PackageIdentityPath $identityPath -PackageArchivePath $archive -ExtractedPackageRoot $package -SyntheticPowerStateProvider $provider|Out-Null}
 function Promote([string]$Path){$json=[IO.File]::ReadAllText($Path);$value=if($PSVersionTable.PSVersion.Major-ge7-and(Get-Command ConvertFrom-Json).Parameters.ContainsKey('DateKind')){$json|ConvertFrom-Json -DateKind String}else{Convert-DateValuesToStrings (ConvertFrom-StrictHumanDesignReviewJson -Json $json -Description 'collector soak fixture')};$value.evidenceClassification='PackagedCompatibilitySoak';$value.evidenceBoundary.evidenceClass='PackagedCompatibilitySoak';$value|Add-Member NoteProperty runNonce $runNonce;Write-RendererPackageCanonicalJson $value $Path $repo;$value};$ac=Promote $acPath;$battery=Promote $batteryPath
 $rawPath=Join-Path $evidence 'performance\raw.json';& (Join-Path $rendererRoot 'Invoke-V02PerformanceMeasurement.ps1') -Synthetic -DestinationPath $rawPath -EvidenceRoot $evidence -RepositoryRoot $repo -SyntheticSoakBins (@($ac.soakBins)+@($battery.soakBins))|Out-Null;$rawBytes=[IO.File]::ReadAllBytes($rawPath);$rawText=(New-Object Text.UTF8Encoding($false,$true)).GetString($rawBytes).TrimEnd("`r","`n");$rawSha=(Get-FileHash $rawPath -Algorithm SHA256).Hash;$rawCanonical=Get-HumanDesignReviewSha256ForText $rawText
 $serverProcess=[Diagnostics.Process]::GetCurrentProcess();$serverPath=$serverProcess.MainModule.FileName;$serverSha=(Get-FileHash -LiteralPath $serverPath -Algorithm SHA256).Hash;$serverStart=[DateTimeOffset]$serverProcess.StartTime.ToUniversalTime();$base=[DateTimeOffset]::UtcNow.AddMinutes(1);$acquisitions=@();for($i=0;$i-lt24;$i++){$order=if($i-lt12){'AB'}else{'BA'};$within=$i%12;$pair=[int][Math]::Floor($within/2);$mode=if($order-eq'AB'){if($within%2-eq0){'a'}else{'b'}}else{if($within%2-eq0){'b'}else{'a'}};$acquisitions+=[pscustomobject][ordered]@{sequenceNumber=$i;order=$order;isWarmup=($pair-eq0);repetitionOrdinal=if($pair-eq0){0}else{$pair-1};semanticMode=$mode;requestedMode=if($mode-eq'a'){'Hardware'}else{'SoftwareOnly'};appProcessId=1000+$i;appStartUtc=$base.AddSeconds($i*10).ToString('O');appPath=(Join-Path $package 'HerdrOps.App.exe');appSha256=$app.Sha256;coreProcessId=2000;coreStartUtc=$base.AddMinutes(-2).ToString('O');corePath=(Join-Path $package 'HerdrOps.Core.exe');coreSha256=$core.Sha256;serverProcessId=$serverProcess.Id;serverStartUtc=$serverStart.ToString('O');serverPath=$serverPath;serverSha256=$serverSha;nativeProcessRenderMode=if($mode-eq'a'){'Default'}else{'SoftwareOnly'};nativeTier=if($mode-eq'a'){2}else{0};preFirstHwndProof=$true;observedUtc=$base.AddSeconds($i*10+5).ToString('O');boundary='PackagedCompatibilityPerformance-NativeTierComparator-NoPerFrameGpuOrRuntimeCredit'}}
 $binding=[pscustomobject][ordered]@{schemaVersion=1;evidenceClassification='PackagedCompatibilityPerformanceTelemetryBinding-NoRuntimeCredit';runNonce=$runNonce;source=[pscustomobject][ordered]@{commitSha=$commit;treeSha=$tree};package=[pscustomobject][ordered]@{identitySha256=$identityCanonical;identityFileSha256=(Get-FileHash $identityPath -Algorithm SHA256).Hash;profileFileSha256=(Get-FileHash $profilePath -Algorithm SHA256).Hash;archiveSha256=$archiveStable.Sha256;manifestSha256=$manifestStable.Sha256;appSha256=$app.Sha256;coreSha256=$core.Sha256};rawSource=[pscustomobject][ordered]@{relativePath='performance/raw.json';bytes=[long]$rawBytes.Length;fileSha256=$rawSha;canonicalSha256=$rawCanonical};acquisitions=$acquisitions;evidenceBoundary=[pscustomobject][ordered]@{actualHerdrRuntime='NOT_OBSERVED';humanReview='NOT_OBSERVED';release='NOT_OBSERVED';creditGranted=$false}};$bindingPath=Join-Path $evidence 'performance\binding.json';Write-RendererPackageCanonicalJson $binding $bindingPath $repo;$bindingBytes=[IO.File]::ReadAllBytes($bindingPath)
 $marker=[pscustomobject][ordered]@{schemaVersion=1;kind='issue10-performance-transaction-commit';runNonce=$runNonce;raw=[pscustomobject][ordered]@{fileName='raw.json';bytes=[long]$rawBytes.Length;sha256=$rawSha};binding=[pscustomobject][ordered]@{fileName='binding.json';bytes=[long]$bindingBytes.Length;sha256=(Get-FileHash $bindingPath -Algorithm SHA256).Hash};creditGranted=$false};$markerPath=Join-Path $evidence 'performance\performance-commit.json';Write-RendererPackageCanonicalJson $marker $markerPath $repo
 $baseArgs=@{AcSoakMeasurementPath=$acPath;BatterySoakMeasurementPath=$batteryPath;RawPerformancePath=$rawPath;PerformanceBindingPath=$bindingPath;PerformanceCommitPath=$markerPath;EvidenceRoot=$evidence;RepositoryRoot=$repo;RunNonce=$runNonce;PackageIdentityPath=$identityPath;PackageArchivePath=$archive;ExtractedPackageRoot=$package;ExpectedSourceCommit=$commit;ExpectedSourceTree=$tree};$destination=Join-Path $evidence 'composed-good';$result=&$composer @baseArgs -DestinationDirectory $destination;if($result.Runtime-ne'NOT OBSERVED'-or-not(Test-Path $result.PerformanceReceiptPath)-or-not[IO.Path]::GetFullPath($result.PerformanceTelemetryBindingPath).Equals([IO.Path]::GetFullPath($bindingPath),[StringComparison]::OrdinalIgnoreCase)-or$result.PerformanceTelemetryBindingSha256-cne(Get-FileHash $bindingPath -Algorithm SHA256).Hash-or-not[IO.Path]::GetFullPath($result.PerformanceTransactionCommitPath).Equals([IO.Path]::GetFullPath($markerPath),[StringComparison]::OrdinalIgnoreCase)-or$result.PerformanceTransactionCommitSha256-cne(Get-FileHash $markerPath -Algorithm SHA256).Hash){throw 'Executable composer positive path failed or discarded sidecar/commit authority.'};Pass 'collector-derived AC/Battery/raw and bound telemetry compose downstream receipts'
 Reject 'composer no-clobber' {&$composer @baseArgs -DestinationDirectory $destination} 'already exists'
 foreach($case in @(@('nonce','runNonce','0'*32),@('source','source.commitSha','0'*40),@('package','package.appSha256','0'*64),@('raw','rawSource.fileSha256','0'*64),@('app-reuse','acquisitions.1.appProcessId',1000),@('core-transplant','acquisitions.2.coreProcessId',2001),@('server-transplant','acquisitions.3.serverProcessId',3001),@('core-start-transplant','acquisitions.2.coreStartUtc',$base.AddMinutes(-3).ToString('O')),@('server-start-transplant','acquisitions.3.serverStartUtc',$serverStart.AddSeconds(1).ToString('O')),@('warmup-map','acquisitions.2.isWarmup',$true),@('repetition-map','acquisitions.4.repetitionOrdinal',4),@('order-map','acquisitions.12.order','AB'))){$bad=Clone $binding;$parts=$case[1].Split('.');if($parts[0]-eq'acquisitions'){$bad.acquisitions[[int]$parts[1]].($parts[2])=$case[2]}else{$target=$bad;for($j=0;$j-lt$parts.Length-1;$j++){$target=$target.($parts[$j])};$target.($parts[-1])=$case[2]};$badPath=Join-Path $evidence ("performance\bad-$($case[0]).json");Write-RendererPackageCanonicalJson $bad $badPath $repo;$badBytes=[IO.File]::ReadAllBytes($badPath);$badMarker=Clone $marker;$badMarker.binding.fileName=[IO.Path]::GetFileName($badPath);$badMarker.binding.bytes=[long]$badBytes.Length;$badMarker.binding.sha256=(Get-FileHash $badPath -Algorithm SHA256).Hash;$badMarkerPath=Join-Path $evidence ("performance\bad-$($case[0])-commit.json");Write-RendererPackageCanonicalJson $badMarker $badMarkerPath $repo;$args=$baseArgs.Clone();$args.PerformanceBindingPath=$badPath;$args.PerformanceCommitPath=$badMarkerPath;Reject "composer rejects $($case[0]) transplant/tamper" {&$composer @args -DestinationDirectory (Join-Path $evidence ("out-$($case[0])"))}}
 $rollback=Join-Path $evidence 'compose-rollback';Reject 'composer rollback before commit' {&$composer @baseArgs -DestinationDirectory $rollback -TestFaultInjectionStage BeforeCommit} 'Injected failure';if(Test-Path $rollback){throw 'Composer rollback exposed destination.'}
 [pscustomobject][ordered]@{EvidenceClassification='ExecutableSyntheticComposerSelftest-NoRuntimeCredit';PositiveCases=$passed;NegativeCases=$negative;Status='PASS'}|Format-Table
}finally{if(Test-Path $temp){Remove-Item -LiteralPath $temp -Recurse -Force -ErrorAction SilentlyContinue}}
