#requires -Version 5.1
[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$RawPerformancePath,
    [Parameter(Mandatory=$true)][string]$PerformanceBindingPath,
    [Parameter(Mandatory=$true)][string]$PerformanceCommitPath,
    [Parameter(Mandatory=$true)][string]$DestinationDirectory,
    [Parameter(Mandatory=$true)][string]$EvidenceRoot,
    [Parameter(Mandatory=$true)][string]$RepositoryRoot,
    [Parameter(Mandatory=$true)][string]$RunNonce,
    [Parameter(Mandatory=$true)][string]$PackageIdentityPath,
    [Parameter(Mandatory=$true)][string]$PackageArchivePath,
    [Parameter(Mandatory=$true)][string]$ExtractedPackageRoot,
    [Parameter(Mandatory=$true)][string]$ExpectedSourceCommit,
    [Parameter(Mandatory=$true)][string]$ExpectedSourceTree
)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
$rendererRoot=Join-Path $PSScriptRoot '..\v0.2-renderer-compatibility'
. (Join-Path $rendererRoot 'RendererCompatibility.Common.ps1')
. (Join-Path $PSScriptRoot '..\lib\V02RuntimePackageBinding.ps1')
function Exact($v,[string[]]$n,[string]$c){Assert-RendererExactProperties $v $n $c}
function Resolve-InRoot([string]$root,[string]$path,[string]$context){$p=if([IO.Path]::IsPathRooted($path)){[IO.Path]::GetFullPath($path)}else{[IO.Path]::GetFullPath((Join-Path $root $path))};Assert-RendererNonReparsePath $root $p $context;if($p-cne$root-and-not$p.StartsWith($root+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)){throw "$context escaped the evidence root."};$p}
function Read-Held([string]$root,[string]$path,[string]$context,[string]$repo){$h=Get-RendererStableFileIdentity $root $path $context -IncludeBytes -KeepOpen;$json=(New-Object Text.UTF8Encoding($false,$true)).GetString($h.Content);$v=ConvertFrom-StrictHumanDesignReviewJson $json $context;if($PSVersionTable.PSVersion.Major-ge7-and(Get-Command ConvertFrom-Json).Parameters.ContainsKey('DateKind')){$v=$json|ConvertFrom-Json -DateKind String};$canonical=ConvertTo-RendererCanonicalJson $v $repo;if($canonical-cne$json.TrimEnd("`r","`n")){$h.Stream.Dispose();throw "$context must be canonical JCS."};[pscustomobject]@{Held=$h;Value=$v;CanonicalSha256=Get-HumanDesignReviewSha256ForText $canonical}}
function Rel([string]$root,[string]$path,[string]$context){$r=[IO.Path]::GetFullPath($path).Substring($root.Length).TrimStart('\','/').Replace('\','/');Assert-RendererRelativePath $r $context;$r}
$root=[IO.Path]::GetFullPath($EvidenceRoot).TrimEnd('\','/');$repo=[IO.Path]::GetFullPath($RepositoryRoot)
if($RunNonce-cnotmatch'^[0-9a-f]{32}$'-or$ExpectedSourceCommit-cnotmatch'^[0-9a-f]{40}$'-or$ExpectedSourceTree-cnotmatch'^[0-9a-f]{40}$'){throw 'Run/source identity format is invalid.'}
$git=Get-RendererGitIdentity $repo;if($git.CommitSha-cne$ExpectedSourceCommit-or$git.TreeSha-cne$ExpectedSourceTree){throw 'Repository HEAD does not equal the requested Issue #10 candidate.'}
$package=Resolve-V02RuntimePackageBinding -IdentityPath $PackageIdentityPath -ArchivePath $PackageArchivePath -PackageRoot $ExtractedPackageRoot -RepositoryRoot $repo -ProfilePath (Join-Path $repo 'tools\packaging\v0.2\package-identity-profile.json') -ExpectedSourceCommit $ExpectedSourceCommit -ExpectedSourceTree $ExpectedSourceTree
$rawPath=Resolve-InRoot $root $RawPerformancePath 'Raw performance observations';$bindingPath=Resolve-InRoot $root $PerformanceBindingPath 'Performance telemetry binding';$commitPath=Resolve-InRoot $root $PerformanceCommitPath 'Performance transaction commit';$dest=Resolve-InRoot $root $DestinationDirectory 'Issue #10 performance output'
if(Test-Path -LiteralPath $dest){throw 'Issue #10 performance output already exists; refusing to clobber.'};$parent=Split-Path -Parent $dest;if(-not(Test-Path -LiteralPath $parent)){[IO.Directory]::CreateDirectory($parent)|Out-Null};$stage=Join-Path $parent ('.issue10-performance-'+[Guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($stage)|Out-Null
$reads=@();$holds=@()
try{
 foreach($leaf in @(@($package.IdentityPath,$package.IdentityFileSha256,'Package identity'),@($package.ProfilePath,$package.ProfileFileSha256,'Package profile'),@($package.ArchivePath,$package.ArchiveSha256,'Package archive'),@($package.ManifestPath,$package.ManifestSha256,'Package manifest'),@($package.AppPath,$package.AppSha256,'Package App'),@($package.CorePath,$package.CoreSha256,'Package Core'))){$h=Get-RendererStableFileIdentity (Split-Path -Parent $leaf[0]) $leaf[0] $leaf[2] -KeepOpen;if($h.Sha256-cne$leaf[1]){$h.Stream.Dispose();throw "$($leaf[2]) changed after package validation."};$holds+=$h}
 $raw=Read-Held $root $rawPath 'Raw performance observations' $repo;$binding=Read-Held $root $bindingPath 'Performance telemetry binding' $repo;$commit=Read-Held $root $commitPath 'Performance transaction commit' $repo;$reads=@($raw,$binding,$commit)
 Exact $raw.Value @('orders') 'Raw performance observations'
 $b=$binding.Value;Exact $b @('schemaVersion','evidenceClassification','runNonce','source','session','package','rawSource','acquisitions','evidenceBoundary') 'Performance telemetry binding';Assert-RendererPositiveInteger $b.schemaVersion 'Performance telemetry binding schemaVersion';if([long]$b.schemaVersion-ne3-or$b.runNonce-cne$RunNonce-or$b.evidenceClassification-cne'PackagedCompatibilityPerformanceTelemetryBinding-NoRuntimeCredit'){throw 'Performance telemetry binding is not current schema-v3.'};Exact $b.source @('commitSha','treeSha') 'Performance source';if($b.source.commitSha-cne$ExpectedSourceCommit-or$b.source.treeSha-cne$ExpectedSourceTree){throw 'Performance telemetry source is stale.'}
 Exact $b.session @('kind','name','sessionId','transport','elevated','userScope') 'Performance session';Assert-RendererNonnegativeInteger $b.session.sessionId 'Performance sessionId';Assert-RendererBoolean $b.session.elevated 'Performance elevated';if($b.session.kind-cne'LocalConsole'-or$b.session.transport-cne'Physical'-or[bool]$b.session.elevated-or$b.session.userScope-cne'SingleUser'){throw 'Performance session is not the governed local non-elevated single-user session.'}
 Exact $b.package @('identitySha256','identityFileSha256','profileFileSha256','archiveSha256','manifestSha256','appSha256','coreSha256') 'Performance package';if($b.package.identitySha256-cne$package.ReceiptSha256-or$b.package.identityFileSha256-cne$package.IdentityFileSha256-or$b.package.profileFileSha256-cne$package.ProfileFileSha256-or$b.package.archiveSha256-cne$package.ArchiveSha256-or$b.package.manifestSha256-cne$package.ManifestSha256-or$b.package.appSha256-cne$package.AppSha256-or$b.package.coreSha256-cne$package.CoreSha256){throw 'Performance package binding is stale.'}
 Exact $b.rawSource @('relativePath','bytes','fileSha256','canonicalSha256') 'Performance raw binding';Assert-RendererPositiveInteger $b.rawSource.bytes 'Performance raw bytes';if($b.rawSource.relativePath-cne(Rel $root $rawPath 'Performance raw relativePath')-or[long]$b.rawSource.bytes-ne[long]$raw.Held.Bytes-or$b.rawSource.fileSha256-cne$raw.Held.Sha256-or$b.rawSource.canonicalSha256-cne$raw.CanonicalSha256){throw 'Performance telemetry does not bind the held raw evidence.'}
 $items=@($b.acquisitions);if($items.Count-ne24){throw 'Performance telemetry must contain exactly 24 AB/BA acquisitions.'};for($i=0;$i-lt24;$i++){Assert-RendererNonnegativeInteger $items[$i].sequenceNumber "Performance acquisition $i sequenceNumber";$expected=if($i-lt12){'AB'}else{'BA'};if([long]$items[$i].sequenceNumber-ne$i-or$items[$i].order-cne$expected){throw 'Performance acquisition order/sequence is invalid.'}}
 Exact $b.evidenceBoundary @('actualHerdrRuntime','release','creditGranted') 'Performance boundary';Assert-RendererBoolean $b.evidenceBoundary.creditGranted 'Performance creditGranted';if($b.evidenceBoundary.actualHerdrRuntime-cne'NOT_OBSERVED'-or$b.evidenceBoundary.release-cne'NOT_OBSERVED'-or[bool]$b.evidenceBoundary.creditGranted){throw 'Performance telemetry inflated evidence credit.'}
 $c=$commit.Value;Exact $c @('schemaVersion','kind','runNonce','raw','binding','creditGranted') 'Performance transaction commit';Exact $c.raw @('fileName','bytes','sha256') 'Commit raw';Exact $c.binding @('fileName','bytes','sha256') 'Commit binding';Assert-RendererPositiveInteger $c.schemaVersion 'Commit schemaVersion';Assert-RendererBoolean $c.creditGranted 'Commit creditGranted';if([long]$c.schemaVersion-ne1-or$c.kind-cne'issue10-performance-transaction-commit'-or$c.runNonce-cne$RunNonce-or[bool]$c.creditGranted-or$c.raw.fileName-cne[IO.Path]::GetFileName($rawPath)-or$c.binding.fileName-cne[IO.Path]::GetFileName($bindingPath)-or$c.raw.sha256-cne$raw.Held.Sha256-or$c.binding.sha256-cne$binding.Held.Sha256-or[long]$c.raw.bytes-ne[long]$raw.Held.Bytes-or[long]$c.binding.bytes-ne[long]$binding.Held.Bytes){throw 'Performance transaction commit does not bind held evidence and exact leaf names.'}
 $id=Get-Item $package.IdentityPath;$profile=Get-Item $package.ProfilePath;$archive=Get-Item $package.ArchivePath;$app=Get-Item $package.AppPath;$core=Get-Item $package.CorePath
 $prov=[pscustomobject][ordered]@{runNonce=$RunNonce;candidate=[pscustomobject][ordered]@{commitSha=$ExpectedSourceCommit;treeSha=$ExpectedSourceTree};package=[pscustomobject][ordered]@{profileId=$package.ProfileId;receipt=[pscustomobject][ordered]@{relativePath=Rel $root $package.IdentityPath 'Identity';bytes=[long]$id.Length;fileSha256=$package.IdentityFileSha256;canonicalSha256=$package.ReceiptSha256};archive=[pscustomobject][ordered]@{relativePath=Rel $root $package.ArchivePath 'Archive';fileName=$archive.Name;bytes=[long]$archive.Length;sha256=$package.ArchiveSha256};packageRootRelativePath=Rel $root $package.PackageRoot 'Package root';components=[pscustomobject][ordered]@{app=[pscustomobject][ordered]@{relativePath=Rel $root $package.AppPath 'App';bytes=[long]$app.Length;sha256=$package.AppSha256};core=[pscustomobject][ordered]@{relativePath=Rel $root $package.CorePath 'Core';bytes=[long]$core.Length;sha256=$package.CoreSha256}}};profile=[pscustomobject][ordered]@{id=$package.ProfileId;relativePath='tools/packaging/v0.2/package-identity-profile.json';bytes=[long]$profile.Length;fileSha256=$package.ProfileFileSha256;canonicalSha256=$package.ProfileCanonicalSha256};referenceHost=[pscustomobject][ordered]@{profileId=$script:RendererProfileId;profileSha256=$package.ReferenceHostProfileSha256};renderer=[pscustomobject][ordered]@{policy='software-only-process-wide';wpfProcessRenderMode='SoftwareOnly';policySha256=$package.RendererPolicySha256};session=$b.session;performanceTelemetryBinding=[pscustomobject][ordered]@{relativePath=Rel $root $bindingPath 'Binding';bytes=[long]$binding.Held.Bytes;fileSha256=$binding.Held.Sha256;canonicalSha256=$binding.CanonicalSha256};performanceTransactionCommit=[pscustomobject][ordered]@{relativePath=Rel $root $commitPath 'Commit';bytes=[long]$commit.Held.Bytes;fileSha256=$commit.Held.Sha256;canonicalSha256=$commit.CanonicalSha256}}
 $receipt=& (Join-Path $rendererRoot 'New-V02PerformanceEvidenceReceipt.ps1') -RawObservations $raw.Value -RawSourcePath $rawPath -DestinationDirectory (Join-Path $stage 'performance') -CandidateProvenance $prov -EvidenceRoot $root -RepositoryRoot $repo
 $packageReceipt=Read-RendererCanonicalPackageReceipt $package.IdentityPath $repo
 $approvedLimits=[pscustomobject][ordered]@{cpuMaximumPercent=1;eventToWpfP95Milliseconds=250;cpuRegressionMaximumPercent=10;cpuRegressionMaximumPercentagePoints=0.5;latencyRegressionMaximumPercent=10;uiStallP95Milliseconds=50;uiStallMaximumMilliseconds=100;workingSetMaximumBytes=267386880}
 if((Assert-RendererPerformanceReceipt $receipt.Binding $root $repo $approvedLimits $prov -ExpectedPackageReceipt $packageReceipt.Identity -ExpectedAcquisitionPackageRoot $package.PackageRoot)-cne'PASS'){throw 'Staged performance receipt failed full shared validation.'}
 foreach($r in $reads){Assert-RendererStableFileLease $r.Held $root $r.Held.FinalPath 'Issue #10 performance input'};foreach($h in $holds){Assert-RendererStableFileLease $h (Split-Path -Parent $h.FinalPath) $h.FinalPath 'Issue #10 package input'}
 if(Test-Path $dest){throw 'Issue #10 performance output appeared concurrently.'};[IO.Directory]::Move($stage,$dest);$stage=$null
 [pscustomobject][ordered]@{SchemaVersion=4;EvidenceClassification='Issue10PerformanceCandidate-NoRuntimeCredit';PerformanceReceiptPath=(Join-Path $dest 'performance\performance-receipt.json');PerformanceReceiptSha256=$receipt.FileSha256;RawPerformancePath=$rawPath;RawPerformanceSha256=$raw.Held.Sha256;PerformanceTelemetryBindingPath=$bindingPath;PerformanceTelemetryBindingSha256=$binding.Held.Sha256;PerformanceTransactionCommitPath=$commitPath;PerformanceTransactionCommitSha256=$commit.Held.Sha256;RunNonce=$RunNonce;Runtime='NOT_OBSERVED';Release='NOT_OBSERVED';CreditGranted=$false}
}finally{foreach($r in $reads){if($null-ne$r.Held.Stream){$r.Held.Stream.Dispose()}};foreach($h in $holds){if($null-ne$h.Stream){$h.Stream.Dispose()}};if($null-ne$stage-and(Test-Path $stage)){Remove-Item -LiteralPath $stage -Recurse -Force}}
