[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'V02Issue10Acceptance.Common.ps1')

$script:Passed = 0
$script:Failed = 0

function Pass-Test {
    param([Parameter(Mandatory = $true)][string]$Name)
    $script:Passed++
    Write-Host "PASS $Name"
}

function Assert-Throws {
    param([Parameter(Mandatory = $true)][scriptblock]$Action,[Parameter(Mandatory = $true)][string]$Name,[string]$Pattern)
    $failed = $false
    $message = $null
    try { & $Action | Out-Null } catch { $failed = $true; $message = [string]$_.Exception.Message }
    if (-not $failed) { throw "Hostile test did not fail closed: $Name" }
    if (-not [string]::IsNullOrWhiteSpace($Pattern) -and $message -notmatch $Pattern) { throw "Hostile test reached the wrong guard for '$Name'. Pattern='$Pattern' Message='$message'" }
    Pass-Test "$Name [$message]"
}

function Write-FixtureJson {
    param([Parameter(Mandatory = $true)][string]$Path,[Parameter(Mandatory = $true)]$Value)
    $parent = Split-Path -Parent $Path
    if (-not (Test-Path -LiteralPath $parent -PathType Container)) { New-Item -ItemType Directory -Path $parent -Force | Out-Null }
    [IO.File]::WriteAllText($Path, (($Value | ConvertTo-Json -Depth 100 -Compress) + "`n"), [Text.UTF8Encoding]::new($false, $true))
}

function New-Sample {
    param([int]$Cpu = 50,[long]$WorkingSet = 104857600,[long]$Latency = 100000,[long]$Stall = 10000)
    [pscustomobject][ordered]@{
        cpuBasisPoints = $Cpu
        workingSetMaximumBytes = $WorkingSet
        latencyMicroseconds = @((1..20 | ForEach-Object { $Latency }))
        uiStallMicroseconds = @((1..20 | ForEach-Object { $Stall }))
    }
}

function New-PerformanceOrder {
    param([Parameter(Mandatory = $true)][string]$Order,[Parameter(Mandatory = $true)][DateTimeOffset]$StartUtc,[Parameter(Mandatory = $true)][int]$OffsetSeconds)
    $warmup = [pscustomobject][ordered]@{ ordinal = 0; observedUtc = $StartUtc.AddSeconds($OffsetSeconds).ToString('O'); a = (New-Sample); b = (New-Sample) }
    $repetitions = @()
    for ($i = 0; $i -lt 5; $i++) {
        $repetitions += [pscustomobject][ordered]@{ ordinal = $i; observedUtc = $StartUtc.AddSeconds($OffsetSeconds + $i + 1).ToString('O'); a = (New-Sample); b = (New-Sample) }
    }
    [pscustomobject][ordered]@{ order = $Order; warmup = @($warmup); repetitions = @($repetitions) }
}

function New-Provenance {
    param([Parameter(Mandatory = $true)][string]$Commit,[Parameter(Mandatory = $true)][string]$Tree,[Parameter(Mandatory = $true)]$Package,[Parameter(Mandatory = $true)][string]$RunNonce)
    [pscustomobject][ordered]@{
        runNonce = $RunNonce
        candidate = [pscustomobject][ordered]@{ commitSha = $Commit; treeSha = $Tree }
        package = [pscustomobject][ordered]@{
            profileId = [string]$Package.ProfileId
            receipt = [pscustomobject][ordered]@{ relativePath = 'package-identity-receipt.json'; bytes = [long]$Package.IdentityLength; fileSha256 = [string]$Package.IdentityFileSha256; canonicalSha256 = [string]$Package.ReceiptSha256 }
            archive = [pscustomobject][ordered]@{ relativePath = 'HerdrOps-0.2.0-win-x64.zip'; fileName = 'HerdrOps-0.2.0-win-x64.zip'; bytes = [long]$Package.ArchiveLength; sha256 = [string]$Package.ArchiveSha256 }
            packageRootRelativePath = 'package'
            components = [pscustomobject][ordered]@{
                app = [pscustomobject][ordered]@{ relativePath = 'HerdrOps.App.exe'; bytes = [long]$Package.AppLength; sha256 = [string]$Package.AppSha256 }
                core = [pscustomobject][ordered]@{ relativePath = 'HerdrOps.Core.exe'; bytes = [long]$Package.CoreLength; sha256 = [string]$Package.CoreSha256 }
            }
        }
    }
}

function New-I10Fixture {
    $root = Join-Path ([IO.Path]::GetTempPath()) ('herdrops-issue10-defensive-' + [Guid]::NewGuid().ToString('N'))
    New-Item -ItemType Directory -Path $root -Force | Out-Null
    $repositoryRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))
    $commit = (@(& git -C $repositoryRoot rev-parse HEAD)).Trim()
    $tree = (@(& git -C $repositoryRoot rev-parse 'HEAD^{tree}')).Trim()
    $runNonce = [Guid]::NewGuid().ToString('N')
    $evidenceStartedUtc = [DateTimeOffset]::UtcNow.AddHours(-2)
    $packageRoot = Join-Path $root 'package'; New-Item -ItemType Directory -Path $packageRoot -Force | Out-Null
    $appPath = Join-Path $packageRoot 'HerdrOps.App.exe'; $corePath = Join-Path $packageRoot 'HerdrOps.Core.exe'; $manifestPath = Join-Path $packageRoot 'package-manifest.json'
    [IO.File]::WriteAllBytes($appPath, [Text.Encoding]::UTF8.GetBytes('issue10-app-bytes'))
    [IO.File]::WriteAllBytes($corePath, [Text.Encoding]::UTF8.GetBytes('issue10-core-bytes'))
    [IO.File]::WriteAllText($manifestPath, '{"files":["HerdrOps.App.exe","HerdrOps.Core.exe"]}' + "`n", [Text.UTF8Encoding]::new($false, $true))
    $archivePath = Join-Path $root 'HerdrOps-0.2.0-win-x64.zip'; [IO.File]::WriteAllBytes($archivePath, [Text.Encoding]::UTF8.GetBytes('issue10-archive-bytes'))
    $identityObject = [pscustomobject][ordered]@{
        schemaVersion = 1; profileId = 'herdrops-v0.2-package-software-only-issue-149'; issue = 149; packageVersion = '0.2.0'; runtimeIdentifier = 'win-x64'
        source = [pscustomobject][ordered]@{ commitSha = $commit; treeSha = $tree }
        profile = [pscustomobject][ordered]@{ id = 'herdrops-v0.2-package-software-only-issue-149'; relativePath = 'tools/packaging/v0.2/package-identity-profile.json'; bytes = 128; fileSha256 = ('A' * 64); canonicalSha256 = ('B' * 64) }
        archive = [pscustomobject][ordered]@{ relativePath = 'HerdrOps-0.2.0-win-x64.zip'; fileName = 'HerdrOps-0.2.0-win-x64.zip'; bytes = 0; sha256 = ('0' * 64) }
        packageManifest = [pscustomobject][ordered]@{ fileName = 'package-manifest.json'; bytes = 0; sha256 = ('0' * 64); contentSha256 = ('C' * 64); fileCount = 2; totalBytes = 1 }
        components = [pscustomobject][ordered]@{ app = [pscustomobject][ordered]@{ relativePath = 'HerdrOps.App.exe'; bytes = 0; sha256 = ('0' * 64) }; core = [pscustomobject][ordered]@{ relativePath = 'HerdrOps.Core.exe'; bytes = 0; sha256 = ('0' * 64) } }
        referenceHost = [pscustomobject][ordered]@{ profileId = 'herdrops-v0.2-submark-nb-software-only-20260822'; profileSha256 = '96D01ED15A536F2DF50B59B43CFDEB3683DCE8667AE2E7BF6A96124182FE13A3' }
        renderer = [pscustomobject][ordered]@{ policy = 'software-only-process-wide'; wpfProcessRenderMode = 'SoftwareOnly' }
        evidenceBoundary = [pscustomobject][ordered]@{ evidenceClass = 'PackagedCompatibilityPreparation'; runtimeUse = 'not-used'; actualHerdrUsed = $false; runtimeCredit = 'NOT CLAIMED'; releaseCredit = 'NOT CLAIMED' }
    }
    $identityPath = Join-Path $root 'package-identity-receipt.json'; Write-FixtureJson $identityPath $identityObject
    $archiveHeld = Read-I10HeldFile -Path $archivePath -MaximumBytes 100000 -Context 'fixture archive'; $manifestHeld = Read-I10HeldFile -Path $manifestPath -MaximumBytes 100000 -Context 'fixture manifest'; $appHeld = Read-I10HeldFile -Path $appPath -MaximumBytes 100000 -Context 'fixture app'; $coreHeld = Read-I10HeldFile -Path $corePath -MaximumBytes 100000 -Context 'fixture core'
    $identityObject.archive.bytes = $archiveHeld.Length; $identityObject.archive.sha256 = $archiveHeld.Sha256; $identityObject.packageManifest.bytes = $manifestHeld.Length; $identityObject.packageManifest.sha256 = $manifestHeld.Sha256; $identityObject.packageManifest.totalBytes = $appHeld.Length + $coreHeld.Length; $identityObject.components.app.bytes = $appHeld.Length; $identityObject.components.app.sha256 = $appHeld.Sha256; $identityObject.components.core.bytes = $coreHeld.Length; $identityObject.components.core.sha256 = $coreHeld.Sha256; Write-FixtureJson $identityPath $identityObject
    $identityHeld = Read-I10HeldFile -Path $identityPath -MaximumBytes 100000 -Context 'fixture identity'; $identityCanonicalSha256 = Get-I10CanonicalSha256 -Value $identityObject
    $package = [pscustomobject][ordered]@{ IdentityPath = $identityPath; IdentityFileSha256 = $identityHeld.Sha256; ReceiptSha256 = $identityCanonicalSha256; ArchivePath = $archivePath; ArchiveSha256 = $archiveHeld.Sha256; PackageRoot = $packageRoot; ManifestPath = $manifestPath; ManifestSha256 = $manifestHeld.Sha256; AppPath = $appPath; AppSha256 = $appHeld.Sha256; CorePath = $corePath; CoreSha256 = $coreHeld.Sha256; SourceCommit = $commit; SourceTree = $tree; ProfileId = 'herdrops-v0.2-package-software-only-issue-149'; IdentityLength = $identityHeld.Length; ArchiveLength = $archiveHeld.Length; AppLength = $appHeld.Length; CoreLength = $coreHeld.Length }
    $rawOrders = @((New-PerformanceOrder -Order 'AB' -StartUtc $evidenceStartedUtc -OffsetSeconds 1),(New-PerformanceOrder -Order 'BA' -StartUtc $evidenceStartedUtc -OffsetSeconds 20)); $rawValue = [pscustomobject][ordered]@{ orders = @($rawOrders) }
    $rawPath = Join-Path $root 'performance\raw-observations.json'; Write-FixtureJson $rawPath $rawValue; $rawHeld = Read-I10HeldFile -Path $rawPath -MaximumBytes 10000000 -Context 'fixture raw performance'
    $provenance = New-Provenance -Commit $commit -Tree $tree -Package $package -RunNonce $runNonce
    $rawCanonical=Get-I10CanonicalSha256 -Value $rawValue;$acquisitions=@();$acquisitionBase=$evidenceStartedUtc.AddSeconds(1)
    for($i=0;$i-lt24;$i++){$order=if($i-lt12){'AB'}else{'BA'};$within=$i%12;$pair=[int][Math]::Floor($within/2);$mode=if($order-ceq'AB'){if($within%2-eq0){'a'}else{'b'}}else{if($within%2-eq0){'b'}else{'a'}};$acquisitions+=[pscustomobject][ordered]@{sequenceNumber=$i;order=$order;isWarmup=($pair-eq0);repetitionOrdinal=if($pair-eq0){0}else{$pair-1};semanticMode=$mode;requestedMode=if($mode-ceq'a'){'Hardware'}else{'SoftwareOnly'};appProcessId=1000+$i;appStartUtc=$acquisitionBase.AddMilliseconds($i*10).ToString('O');appPath=$package.AppPath;appSha256=$package.AppSha256;coreProcessId=2000;coreStartUtc=$evidenceStartedUtc.ToString('O');corePath=$package.CorePath;coreSha256=$package.CoreSha256;serverProcessId=3000;serverStartUtc=$evidenceStartedUtc.ToString('O');serverPath='C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe';serverSha256=('D'*64);nativeProcessRenderMode=if($mode-ceq'a'){'Default'}else{'SoftwareOnly'};nativeTier=if($mode-ceq'a'){2}else{0};preFirstHwndProof=$true;observedUtc=$acquisitionBase.AddMilliseconds($i*10+5).ToString('O');boundary='PackagedCompatibilityPerformance-NativeTierComparator-NoPerFrameGpuOrRuntimeCredit'}}
    $sidecar=[pscustomobject][ordered]@{schemaVersion=3;evidenceClassification='PackagedCompatibilityPerformanceTelemetryBinding-NoRuntimeCredit';runNonce=$runNonce;source=[pscustomobject][ordered]@{commitSha=$commit;treeSha=$tree};session=[pscustomobject][ordered]@{kind='LocalConsole';name='Issue10PerformanceComparator';sessionId=1;transport='Physical';elevated=$false;userScope='SingleUser'};package=[pscustomobject][ordered]@{identitySha256=$package.ReceiptSha256;identityFileSha256=$package.IdentityFileSha256;profileFileSha256=$identityObject.profile.fileSha256;archiveSha256=$package.ArchiveSha256;manifestSha256=$package.ManifestSha256;appSha256=$package.AppSha256;coreSha256=$package.CoreSha256};rawSource=[pscustomobject][ordered]@{relativePath='performance/raw-observations.json';bytes=$rawHeld.Length;fileSha256=$rawHeld.Sha256;canonicalSha256=$rawCanonical};acquisitions=$acquisitions;evidenceBoundary=[pscustomobject][ordered]@{actualHerdrRuntime='NOT_OBSERVED';release='NOT_OBSERVED';creditGranted=$false}}
    $sidecarPath=Join-Path $root 'performance\performance-telemetry-binding.json';Write-FixtureJson $sidecarPath $sidecar;$sidecarHeld=Read-I10HeldFile -Path $sidecarPath -MaximumBytes 10000000 -Context 'fixture performance sidecar'
    $marker=[pscustomobject][ordered]@{schemaVersion=1;kind='issue10-performance-transaction-commit';runNonce=$runNonce;raw=[pscustomobject][ordered]@{fileName='raw-observations.json';bytes=$rawHeld.Length;sha256=$rawHeld.Sha256};binding=[pscustomobject][ordered]@{fileName='performance-telemetry-binding.json';bytes=$sidecarHeld.Length;sha256=$sidecarHeld.Sha256};creditGranted=$false};$markerPath=Join-Path $root 'performance\performance-commit.json';Write-FixtureJson $markerPath $marker;$markerHeld=Read-I10HeldFile -Path $markerPath -MaximumBytes 1000000 -Context 'fixture performance commit'
    $performanceProvenance=[pscustomobject][ordered]@{runNonce=$provenance.runNonce;candidate=$provenance.candidate;package=$provenance.package;profile=[pscustomobject][ordered]@{id=$identityObject.profile.id;relativePath=$identityObject.profile.relativePath;bytes=$identityObject.profile.bytes;fileSha256=$identityObject.profile.fileSha256;canonicalSha256=$identityObject.profile.canonicalSha256};referenceHost=$identityObject.referenceHost;renderer=[pscustomobject][ordered]@{policy='software-only-process-wide';wpfProcessRenderMode='SoftwareOnly';policySha256='1D37C9C39449556EB30F9AB5B734F0C5411CF4203321AF0B238993D017229E92'};session=[pscustomobject][ordered]@{kind='LocalConsole';name='Issue10PerformanceComparator';sessionId=1;transport='Physical';elevated=$false;userScope='SingleUser'};performanceTelemetryBinding=[pscustomobject][ordered]@{relativePath='performance/performance-telemetry-binding.json';bytes=$sidecarHeld.Length;fileSha256=$sidecarHeld.Sha256;canonicalSha256=(Get-I10CanonicalSha256 -Value $sidecar)};performanceTransactionCommit=[pscustomobject][ordered]@{relativePath='performance/performance-commit.json';bytes=$markerHeld.Length;fileSha256=$markerHeld.Sha256;canonicalSha256=(Get-I10CanonicalSha256 -Value $marker)}}
    $performanceValue = [pscustomobject][ordered]@{ schemaVersion=4; provenance = $performanceProvenance; rawSource = [pscustomobject][ordered]@{ relativePath = 'performance/raw-observations.json'; bytes = $rawHeld.Length; fileSha256 = $rawHeld.Sha256; canonicalSha256 = $rawCanonical }; orders = @($rawOrders); aggregateStatus = 'PASS' }
    $performancePath = Join-Path $root 'performance\receipt.json'; Write-FixtureJson $performancePath $performanceValue
    $state = ('1' * 64); $state2 = ('2' * 64); $state3 = ('3' * 64); $herdrHash = ('A' * 64); $control = 'acceptance-control-v02'; $target = 'agent-lab-v02'; $appReports = @{}; $coreReports = @{}; $gatePaths = @{}
    foreach ($language in @('Thai','English')) {
        $appValue = [pscustomobject][ordered]@{ EvidenceClassification = 'RuntimeCandidate'; Language = $language; FinalLanguage = $language; LanguageChangeCount = 0; LanguageStableThroughFinish = $true; CoreStateObserved = $true; DashboardClosed = $true; UpdateObservedAfterDashboardClose = $true; CoreConnectedAfterDashboardClose = $true; DisconnectObservedAfterDashboardClose = $true; ReconnectObservedAfterDashboardClose = $true; SessionControlInvoked = $false; InitialStateSha256 = $state; PreCloseStateSha256 = $state2; PostCloseStateSha256 = $state3; WidgetLatencyP95Milliseconds = 20.0; ResourceMeasurement = [pscustomobject][ordered]@{ CpuTargetPercent = 1.0; WorkingSetTargetBytes = 267386880L; CombinedMaximumWorkingSetMegabytes = 100.0; CombinedAverageCpuPercent = 0.2; CpuTargetPassed = $true; WorkingSetTargetPassed = $true } }
        $coreValue = [pscustomobject][ordered]@{ EvidenceClassification = 'Runtime'; RuntimeObserved = $true; SnapshotObserved = $true; EventObserved = $true; ReconnectObserved = $true; SessionControlInvoked = $false; InitialStateSha256 = $state; EventStateSha256 = $state2; ReconciledStateSha256 = $state3 }
        $appPath = Join-Path $root ("runtime\$language\app-runtime.json"); $corePath = Join-Path $root ("runtime\$language\core-runtime.json"); Write-FixtureJson $appPath $appValue; Write-FixtureJson $corePath $coreValue; $appReports[$language] = $appPath; $coreReports[$language] = $corePath
        $appHeld = Read-I10HeldFile -Path $appPath -MaximumBytes 1000000 -Context 'fixture app report'; $coreHeld = Read-I10HeldFile -Path $corePath -MaximumBytes 1000000 -Context 'fixture core report'
        $gateText = @('HerdrOps v0.2 Composite Actual Herdr Runtime Acceptance',"RunNonce: $runNonce",("GeneratedUtc: {0}" -f $evidenceStartedUtc.AddSeconds(35).ToString('O')),"ExpectedSourceCommit: $commit", "ExpectedSourceTree: $tree", "SourceCommit: $commit", "SourceTree: $tree", "PreRunSourceCommit: $commit", "PreRunSourceTree: $tree", 'PreRunGitTreeClean: True', "PostRunSourceCommit: $commit", "PostRunSourceTree: $tree", 'PostRunGitTreeClean: True', 'Result: PASS', 'EvidenceClass: Runtime', 'SessionControlInvoked: false', "AcceptanceControlSession: $control", "TargetAgentLabSession: $target", 'SeparateSessionSockets: true', "TargetAgentSessionReference: $target", 'TargetAgentSessionReferenceEvidenceSource: OperatorAttestation', 'TargetAgentSessionReferenceObservableByGate: False', 'TargetAgentSessionReferenceBoundary: The gate records this native Agent/session reference but cannot independently observe or prove restoration of the native Agent session.', 'SnapshotObserved: True', 'EventObserved: True', 'ReconnectObserved: True', 'DashboardClosed: True', 'UpdateAfterDashboardClose: True', 'CoreAcceptedEventKindCheck: PASS', 'SemanticCaptureBindingCheck: PASS', "Language: $language", "PackageIdentityFileSha256: $($package.IdentityFileSha256)", "PackageIdentityReceiptSha256: $($package.ReceiptSha256)", "PackageArchiveSha256: $($package.ArchiveSha256)", "PackageManifestSha256: $($package.ManifestSha256)", "AppSha256: $($package.AppSha256)", "CoreSha256: $($package.CoreSha256)", "HerdrExecutableSha256: $herdrHash", 'WidgetLatencyP95Ms: 20', 'CombinedIdleCpuPercent: 0.2', 'IdleWorkingSetTargetBytes: 267386880', 'CombinedMaximumWorkingSetMB: 100', "AppRuntimeReportPath: $appPath", "AppRuntimeReportSha256: $($appHeld.Sha256)", "CoreRuntimeReportPath: $corePath", "CoreRuntimeReportSha256: $($coreHeld.Sha256)") -join "`n"
        $nativeSessionReference=[pscustomobject][ordered]@{agent='codex';kind='id';source='herdr:codex';value='fixture-native-session'}|ConvertTo-Json -Compress
        $gateText=$gateText.Replace("TargetAgentSessionReference: $target","TargetAgentSessionReference: $nativeSessionReference").Replace('TargetAgentSessionReferenceEvidenceSource: OperatorAttestation','TargetAgentSessionReferenceEvidenceSource: HerdrCliAgentMetadata').Replace('TargetAgentSessionReferenceObservableByGate: False','TargetAgentSessionReferenceObservableByGate: true').Replace('TargetAgentSessionReferenceBoundary: The gate records this native Agent/session reference but cannot independently observe or prove restoration of the native Agent session.','TargetAgentSessionReferenceBoundary: The gate directly observed and exact-bound the same structured native Agent session through Herdr CLI metadata before restart, at reconnect, and through completion.')
        $gatePath = Join-Path $root ("runtime\$language\gate-report.txt"); [IO.File]::WriteAllText($gatePath, $gateText + "`n", [Text.UTF8Encoding]::new($false, $true)); $gatePaths[$language] = $gatePath
    }
    $pngBytes = [byte[]]@(137,80,78,71,13,10,26,10,0,0,0,0); $widgetReportByLanguage = @{}
    foreach ($language in @('Thai','English')) {
        $widgetRoot = Join-Path $root $language; New-Item -ItemType Directory -Path $widgetRoot -Force | Out-Null; $captureNames = @('dashboard.png','compact.png','normal.png','floating.png','blocked.png','done.png'); $captures = @{}
        foreach ($name in $captureNames) { $capturePath = Join-Path $widgetRoot $name; [IO.File]::WriteAllBytes($capturePath, $pngBytes); $captures[$name] = Read-I10HeldFile -Path $capturePath -MaximumBytes 100000 -Context "fixture $name" }
        $widgetValue = [pscustomobject][ordered]@{
            SchemaVersion = 1; EvidenceClassification = 'Issue10WidgetObservation'; Issue = 10; Language = $language; RunNonce = $runNonce
            Source = [pscustomobject][ordered]@{ CommitSha = $commit; TreeSha = $tree }
            Bindings = [pscustomobject][ordered]@{ GateReportSha256 = (Get-I10Lines -Path $gatePaths[$language]).Hash; AppRuntimeReportSha256 = (Read-I10HeldFile -Path $appReports[$language] -MaximumBytes 1000000 -Context 'app').Sha256; CoreRuntimeReportSha256 = (Read-I10HeldFile -Path $coreReports[$language] -MaximumBytes 1000000 -Context 'core').Sha256; PackageIdentityFileSha256 = $package.IdentityFileSha256; PackageIdentityReceiptSha256 = $package.ReceiptSha256; PackageArchiveSha256 = $package.ArchiveSha256; PackageManifestSha256 = $package.ManifestSha256; AppSha256 = $package.AppSha256; CoreSha256 = $package.CoreSha256; HerdrExecutableSha256 = $herdrHash; PerformanceReceiptSha256 = (Read-I10HeldFile -Path $performancePath -MaximumBytes 10000000 -Context 'performance').Sha256; PerformanceTelemetryBindingSha256=$sidecarHeld.Sha256;PerformanceTransactionCommitSha256=$markerHeld.Sha256; ControlSessionIdentity = $control; TargetSessionIdentity = $target }
            Chronology = [pscustomobject][ordered]@{ RuntimeStartUtc = $evidenceStartedUtc.AddSeconds(1).ToString('O'); DashboardObservedUtc = $evidenceStartedUtc.AddSeconds(2).ToString('O'); WidgetObservedUtc = $evidenceStartedUtc.AddSeconds(3).ToString('O'); CapturedUtc = $evidenceStartedUtc.AddSeconds(4).ToString('O'); StateSequence = 3 }
            Dashboard = [pscustomobject][ordered]@{ StateSha256 = $state; CapturePath = 'dashboard.png'; CaptureBytes = $captures['dashboard.png'].Length; CaptureSha256 = $captures['dashboard.png'].Sha256 }
            Widgets = @([pscustomobject][ordered]@{ Name = 'Compact'; StateSha256 = $state; SourceStateSha256 = $state; CapturePath = 'compact.png'; CaptureBytes = $captures['compact.png'].Length; CaptureSha256 = $captures['compact.png'].Sha256 },[pscustomobject][ordered]@{ Name = 'Normal'; StateSha256 = $state; SourceStateSha256 = $state; CapturePath = 'normal.png'; CaptureBytes = $captures['normal.png'].Length; CaptureSha256 = $captures['normal.png'].Sha256 },[pscustomobject][ordered]@{ Name = 'FloatingVertical'; StateSha256 = $state; SourceStateSha256 = $state; CapturePath = 'floating.png'; CaptureBytes = $captures['floating.png'].Length; CaptureSha256 = $captures['floating.png'].Sha256 })
            AttentionStates = @([pscustomobject][ordered]@{ Name = 'Blocked'; Status = 'Blocked'; SemanticFingerprint = ('B' * 64); CapturePath = 'blocked.png'; CaptureBytes = $captures['blocked.png'].Length; CaptureSha256 = $captures['blocked.png'].Sha256 },[pscustomobject][ordered]@{ Name = 'Done'; Status = 'Done'; SemanticFingerprint = ('D' * 64); CapturePath = 'done.png'; CaptureBytes = $captures['done.png'].Length; CaptureSha256 = $captures['done.png'].Sha256 })
            UnknownPolicy = [pscustomobject][ordered]@{ UnknownDataRendersUnknown = $true; OfflineDataRendersUnknown = $true; UnknownState = 'Unknown'; OfflineState = 'Offline'; NoSyntheticSuccess = $true; SyntheticFieldsCount = 0 }
        }
        $widgetPath = Join-Path $widgetRoot 'widget-evidence.json'; Write-FixtureJson $widgetPath $widgetValue; $widgetReportByLanguage[$language] = $widgetPath
    }
    [pscustomobject][ordered]@{ Root = $root; RepositoryRoot = $repositoryRoot; Commit = $commit; Tree = $tree; RunNonce = $runNonce; EvidenceStartedUtc = $evidenceStartedUtc; Package = $package; PackageBinding = $package; PerformancePath = $performancePath; PerformanceSidecarPath=$sidecarPath;PerformanceCommitPath=$markerPath; ThaiWidget = $widgetReportByLanguage['Thai']; EnglishWidget = $widgetReportByLanguage['English']; ThaiGate = $gatePaths['Thai']; EnglishGate = $gatePaths['English']; OutputPath = (Join-Path $root 'candidate\issue10-runtime-candidate.json') }
}

function Invoke-Fixture {
    param([Parameter(Mandatory = $true)]$Fixture,[string]$OutputPath = $Fixture.OutputPath)
    return Invoke-I10Issue10Acceptance -EvidenceRoot $Fixture.Root -ThaiWidgetReportPath $Fixture.ThaiWidget -EnglishWidgetReportPath $Fixture.EnglishWidget -ThaiRuntimeGatePath $Fixture.ThaiGate -EnglishRuntimeGatePath $Fixture.EnglishGate -PerformanceReceiptPath $Fixture.PerformancePath -ExpectedSourceCommit $Fixture.Commit -ExpectedSourceTree $Fixture.Tree -PackageBinding $Fixture.PackageBinding -OutputPath $OutputPath -RunNonce $Fixture.RunNonce -EvidenceStartedUtc $Fixture.EvidenceStartedUtc -FixtureMode
}

function Update-PerformanceSidecarFixture {
    param($Fixture,[scriptblock]$Mutation)
    $sidecar=(Read-I10StrictJson -Path $Fixture.PerformanceSidecarPath -Context 'mutated sidecar').Value;&$Mutation $sidecar;Write-FixtureJson $Fixture.PerformanceSidecarPath $sidecar
    $sidecarHeld=Read-I10HeldFile -Path $Fixture.PerformanceSidecarPath -MaximumBytes 10000000 -Context 'mutated sidecar bytes'
    $marker=(Read-I10StrictJson -Path $Fixture.PerformanceCommitPath -Context 'mutated marker').Value;$marker.binding.bytes=$sidecarHeld.Length;$marker.binding.sha256=$sidecarHeld.Sha256;Write-FixtureJson $Fixture.PerformanceCommitPath $marker
    $markerHeld=Read-I10HeldFile -Path $Fixture.PerformanceCommitPath -MaximumBytes 1000000 -Context 'mutated marker bytes'
    $receipt=(Read-I10StrictJson -Path $Fixture.PerformancePath -Context 'mutated receipt').Value
    $receipt.provenance.performanceTelemetryBinding.bytes=$sidecarHeld.Length;$receipt.provenance.performanceTelemetryBinding.fileSha256=$sidecarHeld.Sha256;$receipt.provenance.performanceTelemetryBinding.canonicalSha256=Get-I10CanonicalSha256 -Value $sidecar
    $receipt.provenance.performanceTransactionCommit.bytes=$markerHeld.Length;$receipt.provenance.performanceTransactionCommit.fileSha256=$markerHeld.Sha256;$receipt.provenance.performanceTransactionCommit.canonicalSha256=Get-I10CanonicalSha256 -Value $marker
    Write-FixtureJson $Fixture.PerformancePath $receipt
}

try {
    $valid = New-I10Fixture
    $result = Invoke-Fixture -Fixture $valid
    if ([long]$result.Candidate.SchemaVersion-ne4-or$null-ne$result.Candidate.PSObject.Properties['Soak']-or$null-ne$result.Candidate.EvidenceBoundary.PSObject.Properties['Human']-or[string]$result.Candidate.EvidenceClassification -cne 'Issue10RuntimeCandidate' -or [string]$result.Candidate.EvidenceBoundary.RuntimeInput -cne 'SYNTHETIC_FIXTURE_BOUND' -or [string]$result.Candidate.EvidenceBoundary.Runtime -cne 'NOT_OBSERVED' -or [string]$result.Candidate.EvidenceBoundary.Release -cne 'NOT_OBSERVED' -or [bool]$result.Candidate.EvidenceBoundary.CreditGranted -or [string]$result.Candidate.RunNonce -cne $valid.RunNonce) { throw 'Valid Issue #10 fixture crossed the v4 evidence boundary or retained removed fields.' }
    Pass-Test 'valid bilingual candidate remains RuntimeCandidate with dual-hash and nonce binding'
    if(Get-Command Test-Json -ErrorAction SilentlyContinue){$candidateSchema=Join-Path $PSScriptRoot 'issue10-runtime-candidate.schema.json';$missingPerformanceField=($result.Candidate|ConvertTo-Json -Depth 100|ConvertFrom-Json -DateKind String);$missingPerformanceField.Performance.PSObject.Properties.Remove('TelemetryBindingPath');if(($missingPerformanceField|ConvertTo-Json -Depth 100|Test-Json -SchemaFile $candidateSchema -ErrorAction SilentlyContinue)){throw 'Issue #10 schema admitted a missing TelemetryBindingPath.'};Pass-Test 'candidate schema rejects missing performance authority field';$extraPerformanceField=($result.Candidate|ConvertTo-Json -Depth 100|ConvertFrom-Json -DateKind String);$extraPerformanceField.Performance|Add-Member unexpectedAuthority 'forbidden';if(($extraPerformanceField|ConvertTo-Json -Depth 100|Test-Json -SchemaFile $candidateSchema -ErrorAction SilentlyContinue)){throw 'Issue #10 schema admitted an extra performance authority field.'};Pass-Test 'candidate schema rejects extra performance authority field'}
    Assert-Throws { Publish-I10NoClobber -Root $valid.Root -Path $result.CandidatePath -Text 'clobber' -Context 'direct no-clobber publication' } 'no-clobber preserves an existing destination' 'clobber|existing destination'
    Assert-Throws { Invoke-Fixture -Fixture $valid } 'replayed run nonce is rejected before reuse' 'replay'

    $stale = New-I10Fixture; $stale.EvidenceStartedUtc = [DateTimeOffset]::UtcNow.AddHours(-7); Assert-Throws { Invoke-Fixture -Fixture $stale } 'stale invocation window is rejected by trusted clock' 'six-hour|trusted'
    $missingRaw = New-I10Fixture; $missingRawValue = (Read-I10StrictJson -Path $missingRaw.PerformancePath -Context 'missing raw hash').Value; $missingRawValue.provenance.package.receipt.fileSha256 = $null; Write-FixtureJson -Path $missingRaw.PerformancePath -Value $missingRawValue; Assert-Throws { Invoke-Fixture -Fixture $missingRaw } 'missing raw package hash fails closed' 'fileSha256'
    $missingCanonical = New-I10Fixture; $missingCanonicalValue = (Read-I10StrictJson -Path $missingCanonical.PerformancePath -Context 'missing canonical hash').Value; $missingCanonicalValue.provenance.package.receipt.canonicalSha256 = $null; Write-FixtureJson -Path $missingCanonical.PerformancePath -Value $missingCanonicalValue; Assert-Throws { Invoke-Fixture -Fixture $missingCanonical } 'missing canonical package hash fails closed' 'canonicalSha256'
    $missingSidecar=New-I10Fixture;$missingSidecarValue=(Read-I10StrictJson -Path $missingSidecar.PerformancePath -Context 'missing sidecar').Value;$missingSidecarValue.provenance.PSObject.Properties.Remove('performanceTelemetryBinding');Write-FixtureJson $missingSidecar.PerformancePath $missingSidecarValue;Assert-Throws {Invoke-Fixture $missingSidecar} 'missing performance sidecar provenance fails closed' 'performanceTelemetryBinding'
    $tamperedSidecar=New-I10Fixture;[IO.File]::AppendAllText($tamperedSidecar.PerformanceSidecarPath,' ');Assert-Throws {Invoke-Fixture $tamperedSidecar} 'tampered performance sidecar bytes fail closed' 'sidecar.*binding|canonical'
    $legacySessionSidecar=New-I10Fixture;Update-PerformanceSidecarFixture $legacySessionSidecar {param($value)$value.schemaVersion=2;$value.session|Add-Member powerSource 'AC';$value.session|Add-Member thermalState 'Nominal'};Assert-Throws {Invoke-Fixture $legacySessionSidecar} 'legacy power and thermal performance sidecar cannot close schema v3' 'unknown, missing|schemaVersion|source/session/package/raw binding'
    $offsetSidecar=New-I10Fixture;Update-PerformanceSidecarFixture $offsetSidecar {param($value)$time=[DateTimeOffset]::Parse([string]$value.acquisitions[0].appStartUtc);$value.acquisitions[0].appStartUtc=$time.ToOffset([TimeSpan]::FromHours(7)).ToString('O')};Assert-Throws {Invoke-Fixture $offsetSidecar} 'nonzero-offset sidecar process timestamp fails exact UTC guard' 'exact round-trip UTC'
    $stringSequenceSidecar=New-I10Fixture;Update-PerformanceSidecarFixture $stringSequenceSidecar {param($value)$value.acquisitions[0].sequenceNumber='0'};Assert-Throws {Invoke-Fixture $stringSequenceSidecar} 'performance sidecar string sequenceNumber fails native integer guard' 'native JSON integer'
    $stringPreHwndSidecar=New-I10Fixture;Update-PerformanceSidecarFixture $stringPreHwndSidecar {param($value)$value.acquisitions[0].preFirstHwndProof='true'};Assert-Throws {Invoke-Fixture $stringPreHwndSidecar} 'performance sidecar string preFirstHwndProof fails native boolean guard' 'native JSON boolean'
    $stringCreditSidecar=New-I10Fixture;Update-PerformanceSidecarFixture $stringCreditSidecar {param($value)$value.evidenceBoundary.creditGranted='false'};Assert-Throws {Invoke-Fixture $stringCreditSidecar} 'performance sidecar string creditGranted fails native boolean guard' 'native JSON boolean'
    $transplantedCommit=New-I10Fixture;$commitValue=(Read-I10StrictJson -Path $transplantedCommit.PerformanceCommitPath -Context 'transplanted commit').Value;$commitValue.runNonce=('0'*32);Write-FixtureJson $transplantedCommit.PerformanceCommitPath $commitValue;$commitHeld=Read-I10HeldFile -Path $transplantedCommit.PerformanceCommitPath -MaximumBytes 1000000 -Context 'transplanted commit';$performanceValue=(Read-I10StrictJson -Path $transplantedCommit.PerformancePath -Context 'transplanted performance').Value;$performanceValue.provenance.performanceTransactionCommit.bytes=$commitHeld.Length;$performanceValue.provenance.performanceTransactionCommit.fileSha256=$commitHeld.Sha256;$performanceValue.provenance.performanceTransactionCommit.canonicalSha256=Get-I10CanonicalSha256 $commitValue;Write-FixtureJson $transplantedCommit.PerformancePath $performanceValue;Assert-Throws {Invoke-Fixture $transplantedCommit} 'transplanted performance commit nonce fails closed' 'transaction commit does not bind|runNonce'
    $stringCommitCredit=New-I10Fixture;$stringCommitValue=(Read-I10StrictJson -Path $stringCommitCredit.PerformanceCommitPath -Context 'string commit credit').Value;$stringCommitValue.creditGranted='false';Write-FixtureJson $stringCommitCredit.PerformanceCommitPath $stringCommitValue;$stringCommitHeld=Read-I10HeldFile -Path $stringCommitCredit.PerformanceCommitPath -MaximumBytes 1000000 -Context 'string commit credit';$stringCommitReceipt=(Read-I10StrictJson -Path $stringCommitCredit.PerformancePath -Context 'string commit receipt').Value;$stringCommitReceipt.provenance.performanceTransactionCommit.bytes=$stringCommitHeld.Length;$stringCommitReceipt.provenance.performanceTransactionCommit.fileSha256=$stringCommitHeld.Sha256;$stringCommitReceipt.provenance.performanceTransactionCommit.canonicalSha256=Get-I10CanonicalSha256 $stringCommitValue;Write-FixtureJson $stringCommitCredit.PerformancePath $stringCommitReceipt;Assert-Throws {Invoke-Fixture $stringCommitCredit} 'performance commit string creditGranted fails native boolean guard' 'native JSON boolean'
    $missingBinding = New-I10Fixture; $missingBinding.PackageBinding.PSObject.Properties.Remove('IdentityFileSha256'); Assert-Throws { Invoke-Fixture -Fixture $missingBinding } 'missing caller raw package binding is rejected' 'IdentityFileSha256'
    $legacyPerformance=New-I10Fixture;$legacyValue=(Read-I10StrictJson $legacyPerformance.PerformancePath 'legacy performance').Value;$legacyValue.schemaVersion=3;Write-FixtureJson $legacyPerformance.PerformancePath $legacyValue;Assert-Throws {Invoke-Fixture $legacyPerformance} 'legacy performance receipt cannot close v4' 'schema-v4'
    $soakShapedReceipt=New-I10Fixture;$soakReceipt=(Read-I10StrictJson $soakShapedReceipt.PerformancePath 'legacy soak-shaped receipt').Value;$soakReceipt|Add-Member soakBins @();Write-FixtureJson $soakShapedReceipt.PerformancePath $soakReceipt;Assert-Throws {Invoke-Fixture $soakShapedReceipt} 'legacy performance soakBins cannot close v4' 'unknown, missing|exactly'

    $unknownGate = New-I10Fixture; [IO.File]::AppendAllText($unknownGate.ThaiGate, "Authority: self-authored`n"); Assert-Throws { Invoke-Fixture -Fixture $unknownGate } 'unknown gate authority field is rejected by grammar' 'unknown field'
    $legacyAttestation=New-I10Fixture;$legacyText=[IO.File]::ReadAllText($legacyAttestation.ThaiGate).Replace('TargetAgentSessionReferenceEvidenceSource: HerdrCliAgentMetadata','TargetAgentSessionReferenceEvidenceSource: OperatorAttestation');[IO.File]::WriteAllText($legacyAttestation.ThaiGate,$legacyText,[Text.UTF8Encoding]::new($false,$true));Assert-Throws {Invoke-Fixture $legacyAttestation} 'legacy operator attestation cannot earn new PASS evidence' 'Herdr CLI Agent metadata'
    $unobservableSession=New-I10Fixture;$unobservableText=[IO.File]::ReadAllText($unobservableSession.EnglishGate).Replace('TargetAgentSessionReferenceObservableByGate: true','TargetAgentSessionReferenceObservableByGate: false');[IO.File]::WriteAllText($unobservableSession.EnglishGate,$unobservableText,[Text.UTF8Encoding]::new($false,$true));Assert-Throws {Invoke-Fixture $unobservableSession} 'unobservable native session cannot earn new PASS evidence' 'directly observable'
    $malformedGate = New-I10Fixture; [IO.File]::AppendAllText($malformedGate.EnglishGate, "ignored free-form text`n"); Assert-Throws { Invoke-Fixture -Fixture $malformedGate } 'malformed ignored gate line is rejected by grammar' 'malformed or ignored'
    $selfAuthored = New-I10Fixture; $identityValue = (Read-I10StrictJson -Path $selfAuthored.Package.IdentityPath -Context 'self-authored identity').Value; $identityValue | Add-Member -NotePropertyName authority -NotePropertyValue 'operator'; Write-FixtureJson -Path $selfAuthored.Package.IdentityPath -Value $identityValue; Assert-Throws { Invoke-Fixture -Fixture $selfAuthored } 'self-authored package authority field is rejected by exact identity schema' 'unknown, missing'

    $swap = New-I10Fixture; $swapState = [pscustomobject]@{ Blocked = $false }; Set-I10TestHook -Hook { param($name,$transaction,$data); if ($name -ceq 'AfterPackageBinding') { foreach ($targetPath in @($swap.Package.IdentityPath,$swap.Package.ArchivePath)) { $replacement = Join-Path $swap.Root ([IO.Path]::GetFileName($targetPath) + '.replacement'); $backup = Join-Path $swap.Root ([IO.Path]::GetFileName($targetPath) + '.backup'); [IO.File]::WriteAllText($replacement, 'replacement'); try { [IO.File]::Replace($replacement, $targetPath, $backup); throw 'replacement unexpectedly succeeded' } catch { if ($_.Exception -is [IO.IOException] -or $_.Exception.InnerException -is [IO.IOException] -or [string]$_.Exception.Message -match 'used by another process|sharing violation|being used') { $swapState.Blocked = $true } else { throw } } } } }; try { $null = Invoke-Fixture -Fixture $swap } finally { Set-I10TestHook -Hook $null }; if (-not $swapState.Blocked) { throw 'post-read package/leaf swap was not blocked by held read handles.' }; Pass-Test 'post-read package and identity leaf replacement is blocked by held handles'
    $hardlink = New-I10Fixture; $hardlinkPath = Join-Path $hardlink.Package.PackageRoot 'identity-hardlink'; Set-I10TestHook -Hook { param($name,$transaction,$data); if ($name -ceq 'AfterEvidenceValidation') { New-Item -ItemType HardLink -Path $hardlinkPath -Target $hardlink.Package.IdentityPath -Force | Out-Null } }; try { Assert-Throws { Invoke-Fixture -Fixture $hardlink } 'hardlink count change reaches final identity guard' 'NumberOfLinks|identity' } finally { Set-I10TestHook -Hook $null; if (Test-Path -LiteralPath $hardlinkPath) { Remove-Item -LiteralPath $hardlinkPath -Force } }
    $fileId = New-I10Fixture; Set-I10TestHook -Hook { param($name,$transaction,$data); if ($name -ceq 'AfterEvidenceValidation') { $held = $transaction.ByPath[[IO.Path]::GetFullPath($fileId.Package.IdentityPath)]; $held.Identity = [pscustomobject]@{ VolumeSerialNumber = $held.Identity.VolumeSerialNumber; FileId = ('F' * 16); NumberOfLinks = $held.Identity.NumberOfLinks; FileAttributes = $held.Identity.FileAttributes; IsReparsePoint = $held.Identity.IsReparsePoint } } }; try { Assert-Throws { Invoke-Fixture -Fixture $fileId } 'FileId change reaches final identity guard' 'FileId changed' } finally { Set-I10TestHook -Hook $null }

    $badPng = New-I10Fixture; $badPngValue = (Read-I10StrictJson -Path $badPng.ThaiWidget -Context 'arbitrary PNG').Value; $badCapture = Join-Path (Split-Path -Parent $badPng.ThaiWidget) 'dashboard.png'; [IO.File]::WriteAllBytes($badCapture, [Text.Encoding]::UTF8.GetBytes('arbitrary png')); $badCaptureHeld = Read-I10HeldFile -Path $badCapture -MaximumBytes 100000 -Context 'arbitrary png'; $badPngValue.Dashboard.CaptureBytes = $badCaptureHeld.Length; $badPngValue.Dashboard.CaptureSha256 = $badCaptureHeld.Sha256; Write-FixtureJson -Path $badPng.ThaiWidget -Value $badPngValue; Assert-Throws { Invoke-Fixture -Fixture $badPng } 'arbitrary PNG bytes fail the capture guard' 'PNG signature'
    $publicationRace = New-I10Fixture; $sentinel = 'publication-race-sentinel'; Set-I10TestHook -Hook { param($name,$transaction,$data); if ($name -ceq 'AfterDestinationCheck') { [IO.File]::WriteAllText([string]$data, $sentinel, [Text.UTF8Encoding]::new($false, $true)) } }; try { Assert-Throws { Invoke-Fixture -Fixture $publicationRace } 'publication race cannot clobber a concurrent destination' 'already exists|clobber|no-clobber' } finally { Set-I10TestHook -Hook $null }; if ([IO.File]::ReadAllText($publicationRace.OutputPath) -cne $sentinel) { throw 'Publication race overwrote the unowned destination.' }; Pass-Test 'publication race preserves the unowned destination'
    $postMoveRace = New-I10Fixture; $postMoveHardlink = Join-Path $postMoveRace.Package.PackageRoot 'identity-post-move-hardlink'; $postMoveState = [pscustomobject]@{ HookReached = $false; HardlinkCreated = $false }; Set-I10TestHook -Hook { param($name,$transaction,$data); if ($name -ceq 'AfterPublishedCandidateVerification') { $postMoveState.HookReached = $true; New-Item -ItemType HardLink -Path $postMoveHardlink -Target $postMoveRace.Package.IdentityPath -Force | Out-Null; $postMoveState.HardlinkCreated = $true } }; try { Assert-Throws { Invoke-Fixture -Fixture $postMoveRace } 'post-move input hardlink reaches the final transaction guard' 'NumberOfLinks changed|transaction after published candidate verification' } finally { Set-I10TestHook -Hook $null; if (Test-Path -LiteralPath $postMoveHardlink) { Remove-Item -LiteralPath $postMoveHardlink -Force } }; if (-not $postMoveState.HookReached -or -not $postMoveState.HardlinkCreated) { throw 'Post-move publication hook did not create the hostile admitted-input hardlink.' }; if (Test-Path -LiteralPath $postMoveRace.OutputPath) { throw 'Post-move rejection left a transaction-owned published candidate.' }; $postMoveStages = @(Get-ChildItem -LiteralPath $postMoveRace.Root -Filter '.issue10-stage-*.json' -File -ErrorAction SilentlyContinue); if ($postMoveStages.Count -ne 0) { throw 'Post-move rejection left a staging candidate.' }; Pass-Test 'post-move input hardlink rejects before authority return and cleans owned publication'

    Pass-Test 'fixture path never starts Herdr, HerdrOps, or an application process'
    [pscustomobject][ordered]@{ EvidenceClassification = 'SyntheticVerifierSelftest'; PositiveCases = $script:Passed; NegativeCases = ($script:Passed - 2); Runtime = 'NOT_OBSERVED'; Release = 'NOT_OBSERVED'; CreditGranted = $false }
}
catch {
    $script:Failed++
    throw
}
