Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$tool=Join-Path $PSScriptRoot 'Test-V02LanguageMatrixAcceptance.ps1';$engine=(Get-Process -Id $PID).Path;$utf8=New-Object Text.UTF8Encoding($false)
. (Join-Path $PSScriptRoot 'lib\V02ReferenceHostProfile.ps1')
$testRoot=Join-Path ([IO.Path]::GetTempPath()) ('herdrops-v02-language-matrix-'+[Guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($testRoot)|Out-Null

function Write-TestText([string]$Path,[string]$Text){$parent=[IO.Path]::GetDirectoryName($Path);if(-not[IO.Directory]::Exists($parent)){[IO.Directory]::CreateDirectory($parent)|Out-Null};[IO.File]::WriteAllText($Path,$Text,$utf8)}
function Hash([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToUpperInvariant()}
function TextHash([string]$Text){$sha=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($sha.ComputeHash($utf8.GetBytes($Text)))).Replace('-','')}finally{$sha.Dispose()}}
function ProgressPayload($e){$c=[Globalization.CultureInfo]::InvariantCulture;$accepted=if($null-eq$e.LastAcceptedStateUtc){''}else{([DateTimeOffset]$e.LastAcceptedStateUtc).ToUniversalTime().ToString('O',$c)};@(([int]$e.Ordinal).ToString($c),[string]$e.Phase,([DateTimeOffset]$e.ObservedUtc).ToUniversalTime().ToString('O',$c),([long]$e.Sequence).ToString($c),$(if([bool]$e.IsCoreConnected){'True'}else{'False'}),$(if([bool]$e.IsLive){'True'}else{'False'}),[string]$e.RuntimeStatus,([DateTimeOffset]$e.LastTransitionUtc).ToUniversalTime().ToString('O',$c),$accepted,([long]$e.ConnectionEpoch).ToString($c),([long]$e.BootstrapCount).ToString($c),([long]$e.EventCount).ToString($c),([long]$e.DisconnectCount).ToString($c),([long]$e.ReconciliationCount).ToString($c),[string]$e.StateSha256,[string]$e.PreviousEntrySha256)-join'|'}
function New-RunFixture {
    param([string]$Root,[string]$Language,[string]$AppLanguage=$Language,[string]$Commit=('a'*40),[string]$Tree=('b'*40),[string]$AppBinary=('E'*64),[string]$CoreBinary=('F'*64),[string]$ProfileId=$script:V02ReferenceHostProfileId,[string]$ProfileSha=$script:V02ReferenceHostProfileSha256,[string]$ReferenceSchemaSha=$script:V02ReferenceHostSchemaSha256,[string]$Result='PASS')
    [IO.Directory]::CreateDirectory($Root)|Out-Null;$captureRoot=Join-Path $Root 'captures';[IO.Directory]::CreateDirectory($captureRoot)|Out-Null;$culture=if($AppLanguage-ceq'Thai'){'th-TH'}else{'en-US'};$s1='1'*64;$s2='2'*64;$s3='3'*64;$s4='4'*64
    $catalog=[ordered]@{'dashboard-overview'=@(1,$s1);'dashboard-live-organization'=@(1,$s1);'dashboard-agent-detail'=@(1,$s1);'widget-compact'=@(1,$s1);'widget-normal'=@(1,$s1);'widget-floating-vertical'=@(1,$s1);'dashboard-overview-after-event'=@(2,$s2);'widget-floating-vertical-after-dashboard-close'=@(4,$s4)}
    $captures=@();foreach($item in $catalog.GetEnumerator()){ $path=Join-Path $captureRoot ($item.Key+'.png');Write-TestText $path ('synthetic-'+$item.Key);$captures+=[ordered]@{Name=$item.Key;Path=[IO.Path]::GetFullPath($path);Sha256=(Hash $path);PixelWidth=10;PixelHeight=10;StateSequence=[long]$item.Value[0];StateSha256=$item.Value[1];Language=$AppLanguage;LanguageCultureName=$culture} }
    $changeA=[ordered]@{TerminalId='term-a';WorkspaceId='w1';TabId='w1:t1';PaneId='w1:p1';PreviousStatus='Idle';CurrentStatus='Working';PreviousStateChangeSequence=1L;CurrentStateChangeSequence=2L;CurrentAgentKind='opencode';CurrentAgentName='fixture-agent'};$changeB=[ordered]@{TerminalId='term-b';WorkspaceId='w1';TabId='w1:t1';PaneId='w1:p1';PreviousStatus='Idle';CurrentStatus='Working';PreviousStateChangeSequence=3L;CurrentStateChangeSequence=4L;CurrentAgentKind='opencode';CurrentAgentName='fixture-agent'}
    $eventA=[ordered]@{AcceptedEventKind='pane.agent_status_changed';AdmissionPath='direct-event';BaselineSequence=1L;CurrentSequence=2L;BaselineEventCount=0L;CurrentEventCount=1L;BaselineBootstrapCount=1L;CurrentBootstrapCount=1L;BaselineDisconnectCount=0L;CurrentDisconnectCount=0L;BaselineReconciliationCount=0L;CurrentReconciliationCount=1L;CurrentIsCoreConnected=$true;CurrentIsLive=$true;CurrentStateSha256=$s2;ChangeCount=1;Changes=@($changeA)}
    $eventB=[ordered]@{AcceptedEventKind='pane.agent_status_changed';AdmissionPath='direct-event';BaselineSequence=3L;CurrentSequence=4L;BaselineEventCount=1L;CurrentEventCount=2L;BaselineBootstrapCount=2L;CurrentBootstrapCount=2L;BaselineDisconnectCount=1L;CurrentDisconnectCount=1L;BaselineReconciliationCount=2L;CurrentReconciliationCount=3L;CurrentIsCoreConnected=$true;CurrentIsLive=$true;CurrentStateSha256=$s4;ChangeCount=1;Changes=@($changeB)}
    $app=[ordered]@{EvidenceClassification='RuntimeCandidate';CompositeCandidateChecksPassed=$true;SessionControlInvoked=$false;Language=$AppLanguage;LanguageCultureName=$culture;FinalLanguage=$AppLanguage;FinalLanguageCultureName=$culture;LanguageStableThroughFinish=$true;LanguageChangeCount=0;InitialSequence=1L;InitialStateSha256=$s1;PreCloseSequence=2L;PreCloseStateSha256=$s2;PostCloseSequence=4L;PostCloseStateSha256=$s4;EventA=$eventA;EventB=$eventB;ProfileId=$ProfileId;ProfileSha256=$ProfileSha;ResourceMeasurement=[ordered]@{App=[ordered]@{ExecutableSha256=$AppBinary};Core=[ordered]@{ExecutableSha256=$CoreBinary}};Captures=$captures}
    $accepted=[ordered]@{WorkspaceId='w1';TabId='w1:t1';PaneId='w1:p1';AgentStatus='Working';Agent='opencode';AgentName='fixture-agent'};$transitions=@([ordered]@{IngestSequence=1L;ContractStateSha256=$s1;AcceptedEventKind=$null;AcceptedAgentStatusEvent=$null},[ordered]@{IngestSequence=2L;ContractStateSha256=$s2;AcceptedEventKind='pane.agent_status_changed';AcceptedAgentStatusEvent=$accepted},[ordered]@{IngestSequence=3L;ContractStateSha256=$s3;AcceptedEventKind=$null;AcceptedAgentStatusEvent=$null},[ordered]@{IngestSequence=4L;ContractStateSha256=$s4;AcceptedEventKind='pane.agent_status_changed';AcceptedAgentStatusEvent=$accepted})
    $core=[ordered]@{EvidenceClassification='Runtime';RuntimeObserved=$true;SessionControlInvoked=$false;SnapshotObserved=$true;EventObserved=$true;ReconnectObserved=$true;Transitions=$transitions;Admission=[ordered]@{ReleaseId='0.8.2-synthetic-x86_64-pc-windows-msvc';ExecutableSha256=('D'*64);BundledSchemaSha256=('A'*64);Protocol=20}}
    $appPath=Join-Path $Root 'app-runtime.json';$corePath=Join-Path $Root 'core-runtime.json';Write-TestText $appPath ($app|ConvertTo-Json -Depth 12);Write-TestText $corePath ($core|ConvertTo-Json -Depth 8)
    $phases=@('waiting-for-live-state','capturing-live-dashboard-and-widgets','waiting-for-pre-close-update','dashboard-closed-waiting-for-herdr-disconnect','herdr-disconnected-waiting-for-reconnect','herdr-reconnected-waiting-for-post-reconnect-update','waiting-for-idle-stability','measuring-idle-resources','complete');$history=@();$previous='0'*64
    for($i=0;$i-lt9;$i++){$entry=[ordered]@{Ordinal=($i+1);Phase=$phases[$i];ObservedUtc=([DateTimeOffset]::Parse('2026-08-22T00:00:00Z').AddSeconds($i).ToString('O'));Sequence=[long]([Math]::Min($i,4));IsCoreConnected=($i-gt0);IsLive=($i-gt0);RuntimeStatus=$(if($i-eq0){'Starting'}else{'Connected'});LastTransitionUtc='2026-08-22T00:00:00.0000000+00:00';LastAcceptedStateUtc=$null;ConnectionEpoch=$(if($i-lt4){1L}else{2L});BootstrapCount=$(if($i-lt4){1L}else{2L});EventCount=$(if($i-lt3){0L}elseif($i-lt6){1L}else{2L});DisconnectCount=$(if($i-lt4){0L}else{1L});ReconciliationCount=[long]$i;StateSha256=$s4;PreviousEntrySha256=$previous};$entry.CanonicalPayload=ProgressPayload ([pscustomobject]$entry);$entry.EntrySha256=TextHash $entry.CanonicalPayload;$previous=$entry.EntrySha256;$history+=[pscustomobject]$entry}
    $historyPath=Join-Path $Root 'app-progress.json.history.jsonl';Write-TestText $historyPath (($history|ForEach-Object{$_|ConvertTo-Json -Compress -Depth 8})-join[Environment]::NewLine);$progress=[ordered]@{};foreach($p in $history[8].PSObject.Properties){$progress[$p.Name]=$p.Value};$progress.ProgressHistoryPath=[IO.Path]::GetFullPath($historyPath);$progress.History=$history;$progressPath=Join-Path $Root 'app-progress.json';Write-TestText $progressPath ($progress|ConvertTo-Json -Depth 12)
    $lines=@('HerdrOps v0.2 Composite Actual Herdr Runtime Acceptance',"ExpectedSourceCommit: $Commit","ExpectedSourceTree: $Tree","SourceCommit: $Commit","SourceTree: $Tree","PreRunSourceCommit: $Commit","PreRunSourceTree: $Tree",'PreRunGitTreeClean: True',"PostRunSourceCommit: $Commit","PostRunSourceTree: $Tree",'PostRunGitTreeClean: True',"Result: $Result",'EvidenceClass: Runtime','SessionControlInvoked: false',"Language: $AppLanguage",('PackageIdentityReceiptSha256: '+('9'*64)),"AppSha256: $AppBinary","CoreSha256: $CoreBinary",'HerdrReleaseId: 0.8.2-synthetic-x86_64-pc-windows-msvc',('HerdrExecutableSha256: '+('D'*64)),"HerdrOpsCoreExecutableSha256BeforeLaunch: $CoreBinary","HerdrOpsCoreExecutableSha256AfterRun: $CoreBinary","HerdrOpsAppExecutableSha256BeforeLaunch: $AppBinary","HerdrOpsAppExecutableSha256AfterRun: $AppBinary","HerdrOpsCoreExecutableSha256BoundToReports: $CoreBinary","HerdrOpsAppExecutableSha256BoundToReports: $AppBinary","CoreRuntimeReportSha256: $(Hash $corePath)","AppRuntimeReportSha256: $(Hash $appPath)","ProgressHistoryPath: $([IO.Path]::GetFullPath($historyPath))","ProgressHistorySha256: $(Hash $historyPath)",'ProgressHistoryEntries: 9',"ProgressHistoryLastEntrySha256: $previous",('BundledSchemaSha256: '+('A'*64)),'HerdrProtocol: 20',"ReferenceHostProfileId: $ProfileId","ReferenceHostProfileSha256: $ProfileSha","ReferenceHostSchemaSha256: $ReferenceSchemaSha",'RendererPolicyId: software-only-process-wide','WpfProcessRenderMode: SoftwareOnly','SoftwareOnlyThroughout: True','SnapshotObserved: True','EventObserved: True','ReconnectObserved: True','RuntimeWpfCaptures: 8','','CaptureHashes:')
    $lines+=@($captures|ForEach-Object{"SHA256 $($_.Sha256) $($_.Name)"});Write-TestText (Join-Path $Root 'gate-report.txt') ($lines-join [Environment]::NewLine)
    return [pscustomobject]@{Root=$Root;AppPath=$appPath;CorePath=$corePath;ProgressPath=$progressPath;HistoryPath=$historyPath;CaptureRoot=$captureRoot}
}
function Invoke-Matrix([string]$Thai,[string]$English,[string]$Output){$all=@('-NoProfile','-File',$tool,'-ThaiEvidenceDirectory',$Thai,'-EnglishEvidenceDirectory',$English,'-OutputPath',$Output);$previous=$ErrorActionPreference;$ErrorActionPreference='Continue';try{$text=@(& $engine @all 2>&1);$code=$LASTEXITCODE}finally{$ErrorActionPreference=$previous;$global:LASTEXITCODE=0};[pscustomobject]@{ExitCode=$code;Text=($text-join [Environment]::NewLine)}}
function Set-GateField($Fixture,[string]$Name,[string]$Value){$path=Join-Path $Fixture.Root 'gate-report.txt';$text=Get-Content -LiteralPath $path -Raw;$updated=[regex]::Replace($text,"(?m)^$([regex]::Escape($Name)): .+$","${Name}: $Value");if($updated-ceq$text){throw "Gate field was not found: $Name"};Write-TestText $path $updated}
function Refresh-AppHash($Fixture){Set-GateField $Fixture 'AppRuntimeReportSha256' (Hash $Fixture.AppPath)}
function Refresh-CoreHash($Fixture){Set-GateField $Fixture 'CoreRuntimeReportSha256' (Hash $Fixture.CorePath)}
function Pass([string]$Name,[scriptblock]$Body){&$Body;Write-Output "PASS Synthetic: $Name"}
function Expect-Failure([string]$Name,[scriptblock]$Arrange){$case=Join-Path $testRoot ([Guid]::NewGuid().ToString('N'));$thai=New-RunFixture (Join-Path $case 'thai') 'Thai';$english=New-RunFixture (Join-Path $case 'english') 'English';&$Arrange $thai $english;$out=Join-Path $case 'matrix.json';$result=Invoke-Matrix $thai.Root $english.Root $out;if($result.ExitCode-eq 0-or(Test-Path $out)){throw "$Name did not fail closed. $($result.Text)"};Write-Output "PASS Synthetic: $Name"}

try {
    Pass 'happy path emits hash-bound non-release candidate' {
        $case=Join-Path $testRoot 'happy';$thai=New-RunFixture (Join-Path $case 'thai') 'Thai';$english=New-RunFixture (Join-Path $case 'english') 'English';$out=Join-Path $case 'matrix.json';$result=Invoke-Matrix $thai.Root $english.Root $out
        if($result.ExitCode-ne 0){throw $result.Text};$manifest=Get-Content $out -Raw|ConvertFrom-Json
        if($manifest.EvidenceClassification-cne'RuntimeMatrixCandidate'-or$manifest.IndependentHumanReview-cne'NOT_OBSERVED'-or[bool]$manifest.ReleaseCredit-or$manifest.Payload.IndependentHumanReview-cne'NOT_OBSERVED'-or[bool]$manifest.Payload.ReleaseCredit){throw 'Happy manifest boundary fields are wrong.'}
        $payloadJson=ConvertTo-V02Jcs $manifest.Payload;$observed=([BitConverter]::ToString([Security.Cryptography.SHA256]::Create().ComputeHash($utf8.GetBytes($payloadJson)))).Replace('-','');if($observed-cne[string]$manifest.ManifestPayloadSha256){throw 'Manifest payload SHA mismatch.'}
    }
    foreach($caseInfo in @(
        @{Name='mixed source commit';Args=@{Commit=('c'*40)}},
        @{Name='mixed source tree';Args=@{Tree=('d'*40)}},
        @{Name='mixed App binary';Args=@{AppBinary=('B'*64)}},
        @{Name='mixed profile hash';Args=@{ProfileSha=('B'*64)}})) {
        $case=Join-Path $testRoot ([Guid]::NewGuid().ToString('N'));$thai=New-RunFixture (Join-Path $case 'thai') 'Thai';$fixtureArgs=$caseInfo.Args;$english=New-RunFixture -Root (Join-Path $case 'english') -Language 'English' @fixtureArgs;$out=Join-Path $case 'matrix.json';$result=Invoke-Matrix $thai.Root $english.Root $out;if($result.ExitCode-eq 0-or(Test-Path $out)){throw "$($caseInfo.Name) did not fail closed."};Write-Output "PASS Synthetic: $($caseInfo.Name)"
    }
    Expect-Failure 'swapped Thai language' {param($thai,$english);$replacement=New-RunFixture -Root $thai.Root -Language Thai -AppLanguage English}
    Expect-Failure 'duplicate Thai language' {param($thai,$english);$replacement=New-RunFixture -Root $english.Root -Language English -AppLanguage Thai}
    Pass 'same evidence directory rejected' {$case=Join-Path $testRoot 'same-dir';$thai=New-RunFixture $case 'Thai';$out=Join-Path $testRoot 'same-dir-output.json';$result=Invoke-Matrix $thai.Root $thai.Root $out;if($result.ExitCode-eq 0-or(Test-Path $out)){throw 'Same evidence directory did not fail closed.'}}
    Expect-Failure 'shared capture paths rejected' {param($thai,$english);$app=Get-Content $english.AppPath -Raw|ConvertFrom-Json;$thaiApp=Get-Content $thai.AppPath -Raw|ConvertFrom-Json;for($i=0;$i-lt$app.Captures.Count;$i++){$app.Captures[$i].Path=$thaiApp.Captures[$i].Path;$app.Captures[$i].Sha256=$thaiApp.Captures[$i].Sha256};Write-TestText $english.AppPath ($app|ConvertTo-Json -Depth 12);$gate=Get-Content (Join-Path $english.Root 'gate-report.txt') -Raw;$gate=[regex]::Replace($gate,'(?m)^AppRuntimeReportSha256: .+$',"AppRuntimeReportSha256: $(Hash $english.AppPath)");Write-TestText (Join-Path $english.Root 'gate-report.txt') $gate}
    Expect-Failure 'failed gate result rejected' {param($thai,$english);$gate=Get-Content (Join-Path $english.Root 'gate-report.txt') -Raw;$gate=$gate.Replace('Result: PASS','Result: FAIL');Write-TestText (Join-Path $english.Root 'gate-report.txt') $gate}
    Expect-Failure 'gate-declared report hash mismatch rejected' {param($thai,$english);$gate=Get-Content (Join-Path $english.Root 'gate-report.txt') -Raw;$gate=[regex]::Replace($gate,'(?m)^AppRuntimeReportSha256: .+$',('AppRuntimeReportSha256: '+('0'*64)));Write-TestText (Join-Path $english.Root 'gate-report.txt') $gate}
    Pass 'wrong but matching profile rejected' {$case=Join-Path $testRoot 'wrong-profile';$wrong=('B'*64);$thai=New-RunFixture -Root (Join-Path $case 'thai') -Language Thai -ProfileSha $wrong;$english=New-RunFixture -Root (Join-Path $case 'english') -Language English -ProfileSha $wrong;$out=Join-Path $case 'matrix.json';$result=Invoke-Matrix $thai.Root $english.Root $out;if($result.ExitCode-eq 0-or(Test-Path $out)){throw 'Matching unapproved profile did not fail closed.'}}
    Pass 'wrong but matching reference-host schema rejected' {$case=Join-Path $testRoot 'wrong-schema';$wrong=('B'*64);$thai=New-RunFixture -Root (Join-Path $case 'thai') -Language Thai -ReferenceSchemaSha $wrong;$english=New-RunFixture -Root (Join-Path $case 'english') -Language English -ReferenceSchemaSha $wrong;$out=Join-Path $case 'matrix.json';$result=Invoke-Matrix $thai.Root $english.Root $out;if($result.ExitCode-eq 0-or(Test-Path $out)){throw 'Matching unapproved reference-host schema did not fail closed.'}}
    Pass 'output inside accepted evidence rejected' {$case=Join-Path $testRoot 'inside-output';$thai=New-RunFixture (Join-Path $case 'thai') Thai;$english=New-RunFixture (Join-Path $case 'english') English;$out=Join-Path $thai.Root 'matrix.json';$result=Invoke-Matrix $thai.Root $english.Root $out;if($result.ExitCode-eq 0-or(Test-Path $out)){throw 'Output inside accepted evidence did not fail closed.'}}
    Expect-Failure 'post-run final language tamper rejected after report rehash' {param($thai,$english);$app=Get-Content $english.AppPath -Raw|ConvertFrom-Json;$app.FinalLanguage='Thai';Write-TestText $english.AppPath ($app|ConvertTo-Json -Depth 12);Refresh-AppHash $english}
    Expect-Failure 'post-run language culture tamper rejected after report rehash' {param($thai,$english);$app=Get-Content $english.AppPath -Raw|ConvertFrom-Json;$app.FinalLanguageCultureName='th-TH';Write-TestText $english.AppPath ($app|ConvertTo-Json -Depth 12);Refresh-AppHash $english}
    Expect-Failure 'post-run capture state tamper rejected after report rehash' {param($thai,$english);$app=Get-Content $english.AppPath -Raw|ConvertFrom-Json;$app.Captures[0].StateSha256='2'*64;Write-TestText $english.AppPath ($app|ConvertTo-Json -Depth 12);Refresh-AppHash $english}
    Expect-Failure 'post-run accepted-event kind tamper rejected after report rehash' {param($thai,$english);$core=Get-Content $english.CorePath -Raw|ConvertFrom-Json;$core.Transitions[1].AcceptedEventKind='pane.title_changed';Write-TestText $english.CorePath ($core|ConvertTo-Json -Depth 12);Refresh-CoreHash $english}
    Expect-Failure 'post-run RuntimeObserved tamper rejected after report rehash' {param($thai,$english);$core=Get-Content $english.CorePath -Raw|ConvertFrom-Json;$core.RuntimeObserved=$false;Write-TestText $english.CorePath ($core|ConvertTo-Json -Depth 12);Refresh-CoreHash $english}
    Expect-Failure 'post-run JSONL chain tamper rejected after history rehash' {param($thai,$english);$lines=[IO.File]::ReadAllLines($english.HistoryPath);$entry=$lines[4]|ConvertFrom-Json;$entry.EventCount=99;$lines[4]=$entry|ConvertTo-Json -Compress -Depth 8;Write-TestText $english.HistoryPath ($lines-join[Environment]::NewLine);Set-GateField $english 'ProgressHistorySha256' (Hash $english.HistoryPath)}
    Expect-Failure 'post-run app-progress mirror tamper rejected' {param($thai,$english);$progress=Get-Content $english.ProgressPath -Raw|ConvertFrom-Json;$progress.History[2].Phase='tampered';Write-TestText $english.ProgressPath ($progress|ConvertTo-Json -Depth 12)}
    Expect-Failure 'different package receipt rejected' {param($thai,$english);Set-GateField $english 'PackageIdentityReceiptSha256' ('8'*64)}
    Write-Output 'All 22 v0.2 language-matrix cases passed. EvidenceClass: Synthetic.'
} finally {
    if(Test-Path -LiteralPath $testRoot){Remove-Item -LiteralPath $testRoot -Recurse -Force}
}
