Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$tool=Join-Path $PSScriptRoot 'Test-V02LanguageMatrixAcceptance.ps1';$engine=(Get-Process -Id $PID).Path;$utf8=New-Object Text.UTF8Encoding($false)
. (Join-Path $PSScriptRoot 'lib\V02ReferenceHostProfile.ps1')
. (Join-Path $PSScriptRoot 'packaging\v0.2\V02PackageIdentity.Common.ps1')
$testRoot=Join-Path ([IO.Path]::GetTempPath()) ('herdrops-v02-language-matrix-'+[Guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($testRoot)|Out-Null

function Write-TestText([string]$Path,[string]$Text){$parent=[IO.Path]::GetDirectoryName($Path);if(-not[IO.Directory]::Exists($parent)){[IO.Directory]::CreateDirectory($parent)|Out-Null};[IO.File]::WriteAllText($Path,$Text,$utf8)}
function Hash([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToUpperInvariant()}
function TextHash([string]$Text){$sha=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($sha.ComputeHash($utf8.GetBytes($Text)))).Replace('-','')}finally{$sha.Dispose()}}
function ProgressPayload($e){$c=[Globalization.CultureInfo]::InvariantCulture;$accepted=if($null-eq$e.LastAcceptedStateUtc){''}else{([DateTimeOffset]$e.LastAcceptedStateUtc).ToUniversalTime().ToString('O',$c)};@(([int]$e.Ordinal).ToString($c),[string]$e.Phase,([DateTimeOffset]$e.ObservedUtc).ToUniversalTime().ToString('O',$c),([long]$e.Sequence).ToString($c),$(if([bool]$e.IsCoreConnected){'True'}else{'False'}),$(if([bool]$e.IsLive){'True'}else{'False'}),[string]$e.RuntimeStatus,([DateTimeOffset]$e.LastTransitionUtc).ToUniversalTime().ToString('O',$c),$accepted,([long]$e.ConnectionEpoch).ToString($c),([long]$e.BootstrapCount).ToString($c),([long]$e.EventCount).ToString($c),([long]$e.DisconnectCount).ToString($c),([long]$e.ReconciliationCount).ToString($c),[string]$e.StateSha256,[string]$e.PreviousEntrySha256)-join'|'}
function New-PackageFixture {
    $source=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'));$root=Join-Path $testRoot 'package-fixture';$repo=Join-Path $root 'source';$packageRoot=Join-Path $root 'extracted';$archive=Join-Path $root 'HerdrOps-0.2.0-win-x64.zip';$identityPath=Join-Path $root 'identity.json'
    foreach($dir in @((Join-Path $repo 'Plan\reference-hosts'),(Join-Path $repo 'tools\lib'),(Join-Path $repo 'tools\packaging\v0.2'),$packageRoot)){[IO.Directory]::CreateDirectory($dir)|Out-Null}
    foreach($relative in @('Plan\reference-hosts\v0.2.json','Plan\reference-hosts\reference-host-profile.schema.json','tools\lib\V02ReferenceHostProfile.ps1','tools\packaging\Packaging.Common.ps1','tools\packaging\v0.2\package-identity-profile.json','tools\packaging\v0.2\package-identity-receipt.schema.json','tools\packaging\v0.2\V02PackageIdentity.Common.ps1','tools\packaging\v0.2\Test-V02PackageIdentity.ps1')){Copy-Item -LiteralPath (Join-Path $source $relative) -Destination (Join-Path $repo $relative)}
    & git -C $repo init --quiet;& git -C $repo -c user.name=HerdrOps-Test -c user.email=test@example.invalid add --all;& git -C $repo -c user.name=HerdrOps-Test -c user.email=test@example.invalid commit --quiet -m fixture;if($LASTEXITCODE){throw 'Package Git fixture creation failed.'};$global:LASTEXITCODE=0
    $profilePath=Join-Path $repo 'tools\packaging\v0.2\package-identity-profile.json';$profile=Read-V02PackageIdentityProfile $profilePath;$appPath=Join-Path $packageRoot 'HerdrOps.App.exe';$corePath=Join-Path $packageRoot 'HerdrOps.Core.exe';[IO.File]::WriteAllBytes($appPath,[byte[]](11,12,13,14,15));[IO.File]::WriteAllBytes($corePath,[byte[]](21,22,23,24,25,26))
    $manifest=New-V02PackageManifestObject $profile $repo $packageRoot;$manifestPath=Join-Path $packageRoot 'package-manifest.json';Write-V02CanonicalJsonFile $manifest $manifestPath $repo;$manifestStable=Get-V02StableFileIdentity $manifestPath;$inventory=Get-V02PackageRootInventory $packageRoot -ExcludeRelativePath @('package-manifest.json');$app=@($inventory.Entries|Where-Object Path -CEQ 'HerdrOps.App.exe')[0];$core=@($inventory.Entries|Where-Object Path -CEQ 'HerdrOps.Core.exe')[0]
    $null=New-DeterministicPackageArchive -PackageRoot $packageRoot -ArchivePath $archive;$archiveStable=Get-V02StableFileIdentity $archive;$gitId=Get-V02GitIdentity $repo -RequireClean;$profileId=Get-V02PreparationProfileIdentity $profilePath $profile $repo
    $identity=[pscustomobject][ordered]@{schemaVersion=1;profileId=$profile.profileId;issue=149;packageVersion='0.2.0';runtimeIdentifier='win-x64';source=[pscustomobject][ordered]@{commitSha=$gitId.CommitSha;treeSha=$gitId.TreeSha};profile=[pscustomobject][ordered]@{id=$profileId.Id;relativePath=$profileId.RelativePath;bytes=[int64]$profileId.Bytes;fileSha256=$profileId.FileSha256;canonicalSha256=$profileId.CanonicalSha256};archive=[pscustomobject][ordered]@{relativePath=$profile.archiveFileName;fileName=$profile.archiveFileName;bytes=[int64]$archiveStable.Length;sha256=$archiveStable.Sha256};packageManifest=[pscustomobject][ordered]@{fileName='package-manifest.json';bytes=[int64]$manifestStable.Length;sha256=$manifestStable.Sha256;contentSha256=$manifest.contentSha256;fileCount=[int]$manifest.fileCount;totalBytes=[int64]$manifest.totalBytes};components=[pscustomobject][ordered]@{app=[pscustomobject][ordered]@{relativePath='HerdrOps.App.exe';bytes=[int64]$app.Length;sha256=$app.Sha256};core=[pscustomobject][ordered]@{relativePath='HerdrOps.Core.exe';bytes=[int64]$core.Length;sha256=$core.Sha256}};referenceHost=[pscustomobject][ordered]@{profileId=$profile.referenceHost.profileId;profileSha256=$profile.referenceHost.profileSha256};renderer=[pscustomobject][ordered]@{policy=$profile.renderer.policy;wpfProcessRenderMode=$profile.renderer.wpfProcessRenderMode};evidenceBoundary=[pscustomobject][ordered]@{evidenceClass='PackagedCompatibilityPreparation';runtimeUse='not-used';actualHerdrUsed=$false;runtimeCredit='NOT CLAIMED';releaseCredit='NOT CLAIMED'}}
    Write-V02CanonicalJsonFile $identity $identityPath $repo;$receipt=Read-V02CanonicalIdentityReceipt $identityPath $repo;return [pscustomobject]@{RepositoryRoot=$repo;PackageRoot=$packageRoot;ArchivePath=$archive;IdentityPath=$identityPath;ProfilePath=$profilePath;ReceiptSha256=$receipt.ReceiptSha256;ArchiveSha256=$archiveStable.Sha256;ManifestSha256=$manifestStable.Sha256;AppSha256=$app.Sha256;CoreSha256=$core.Sha256;ProfileId=$profile.profileId;Commit=$gitId.CommitSha;Tree=$gitId.TreeSha}
}
$script:packageFixture=New-PackageFixture
function New-RunFixture {
    param([string]$Root,[string]$Language,[string]$AppLanguage=$Language,[string]$Commit=$script:packageFixture.Commit,[string]$Tree=$script:packageFixture.Tree,[string]$AppBinary=$script:packageFixture.AppSha256,[string]$CoreBinary=$script:packageFixture.CoreSha256,[string]$ProfileId=$script:V02ReferenceHostProfileId,[string]$ProfileSha=$script:V02ReferenceHostProfileSha256,[string]$ReferenceSchemaSha=$script:V02ReferenceHostSchemaSha256,[string]$Result='PASS')
    [IO.Directory]::CreateDirectory($Root)|Out-Null;$captureRoot=Join-Path $Root 'captures';[IO.Directory]::CreateDirectory($captureRoot)|Out-Null;$culture=if($AppLanguage-ceq'Thai'){'th-TH'}else{'en-US'};$s1='1'*64;$s2='2'*64;$s3='3'*64;$s4='4'*64
    $catalog=[ordered]@{'dashboard-overview'=@(1,$s1);'dashboard-live-organization'=@(1,$s1);'dashboard-agent-detail'=@(1,$s1);'widget-compact'=@(1,$s1);'widget-normal'=@(1,$s1);'widget-floating-vertical'=@(1,$s1);'dashboard-overview-after-event'=@(2,$s2);'widget-floating-vertical-after-dashboard-close'=@(5,$s4)}
    Add-Type -AssemblyName System.Drawing;$captures=@();foreach($item in $catalog.GetEnumerator()){ $path=Join-Path $captureRoot ($item.Key+'.png');$bitmap=New-Object Drawing.Bitmap(2,2);try{$bitmap.SetPixel(0,0,[Drawing.Color]::Blue);$bitmap.Save($path,[Drawing.Imaging.ImageFormat]::Png)}finally{$bitmap.Dispose()};$captures+=[ordered]@{Name=$item.Key;Path=[IO.Path]::GetFullPath($path);Sha256=(Hash $path);PixelWidth=2;PixelHeight=2;StateSequence=[long]$item.Value[0];StateSha256=$item.Value[1];Language=$AppLanguage;LanguageCultureName=$culture} }
    $changeA=[ordered]@{TerminalId='term-a';WorkspaceId='w1';TabId='w1:t1';PaneId='w1:p1';PreviousStatus='Idle';CurrentStatus='Working';PreviousStateChangeSequence=1L;CurrentStateChangeSequence=2L;CurrentAgentKind='opencode';CurrentAgentName='fixture-agent'};$changeB=[ordered]@{TerminalId='term-b';WorkspaceId='w1';TabId='w1:t1';PaneId='w1:p1';PreviousStatus='Idle';CurrentStatus='Working';PreviousStateChangeSequence=3L;CurrentStateChangeSequence=4L;CurrentAgentKind='opencode';CurrentAgentName='fixture-agent'}
    $eventA=[ordered]@{AcceptedEventKind='pane.agent_status_changed';AdmissionPath='direct-event';BaselineSequence=1L;CurrentSequence=2L;BaselineEventCount=0L;CurrentEventCount=1L;BaselineBootstrapCount=1L;CurrentBootstrapCount=1L;BaselineDisconnectCount=0L;CurrentDisconnectCount=0L;BaselineReconciliationCount=0L;CurrentReconciliationCount=1L;CurrentIsCoreConnected=$true;CurrentIsLive=$true;CurrentStateSha256=$s2;ChangeCount=1;Changes=@($changeA)}
    $eventB=[ordered]@{AcceptedEventKind='pane.agent_status_changed';AdmissionPath='direct-event';BaselineSequence=4L;CurrentSequence=5L;BaselineEventCount=1L;CurrentEventCount=2L;BaselineBootstrapCount=2L;CurrentBootstrapCount=2L;BaselineDisconnectCount=1L;CurrentDisconnectCount=1L;BaselineReconciliationCount=2L;CurrentReconciliationCount=3L;CurrentIsCoreConnected=$true;CurrentIsLive=$true;CurrentStateSha256=$s4;ChangeCount=1;Changes=@($changeB)}
    $app=[ordered]@{EvidenceClassification='RuntimeCandidate';CompositeCandidateChecksPassed=$true;SessionControlInvoked=$false;Language=$AppLanguage;LanguageCultureName=$culture;FinalLanguage=$AppLanguage;FinalLanguageCultureName=$culture;LanguageStableThroughFinish=$true;LanguageChangeCount=0;InitialSequence=1L;InitialStateSha256=$s1;PreCloseSequence=2L;PreCloseStateSha256=$s2;PostCloseSequence=5L;PostCloseStateSha256=$s4;PreRestartConnectionEpoch=1L;ReconnectedConnectionEpoch=2L;PreRestartBootstrapCount=1L;ReconnectedBootstrapCount=2L;PreRestartDisconnectCount=0L;ReconnectedDisconnectCount=1L;DashboardClosedUtc='2026-08-22T00:00:02Z';DisconnectObservedUtc='2026-08-22T00:00:03Z';ReconnectObservedUtc='2026-08-22T00:00:04Z';EventA=$eventA;EventB=$eventB;ProfileId=$ProfileId;ProfileSha256=$ProfileSha;ResourceMeasurement=[ordered]@{App=[ordered]@{ExecutableSha256=$AppBinary};Core=[ordered]@{ExecutableSha256=$CoreBinary}};Captures=$captures}
    $eventB.CurrentSequence=5L
    $accepted=[ordered]@{WorkspaceId='w1';TabId='w1:t1';PaneId='w1:p1';AgentStatus='Working';Agent='opencode';AgentName='fixture-agent'};$base='2026-08-22T00:00:0';$transitions=@([ordered]@{ObservedUtc=$base+'1Z';Status='Connected';IngestSequence=1L;ConnectionEpoch=1L;BootstrapCount=1L;EventCount=0L;DisconnectCount=0L;ReconciliationCount=0L;ContractStateSha256=$s1;AcceptedEventKind=$null;AcceptedAgentStatusEvent=$null},[ordered]@{ObservedUtc=$base+'2Z';Status='Connected';IngestSequence=2L;ConnectionEpoch=1L;BootstrapCount=1L;EventCount=1L;DisconnectCount=0L;ReconciliationCount=1L;ContractStateSha256=$s2;AcceptedEventKind='pane.agent_status_changed';AcceptedAgentStatusEvent=$accepted},[ordered]@{ObservedUtc=$base+'3Z';Status='Reconnecting';IngestSequence=2L;ConnectionEpoch=1L;BootstrapCount=1L;EventCount=1L;DisconnectCount=1L;ReconciliationCount=2L;ContractStateSha256=$s2;AcceptedEventKind=$null;AcceptedAgentStatusEvent=$null},[ordered]@{ObservedUtc=$base+'4Z';Status='Connected';IngestSequence=3L;ConnectionEpoch=2L;BootstrapCount=2L;EventCount=1L;DisconnectCount=1L;ReconciliationCount=2L;ContractStateSha256=$s3;AcceptedEventKind=$null;AcceptedAgentStatusEvent=$null},[ordered]@{ObservedUtc=$base+'5Z';Status='Connected';IngestSequence=5L;ConnectionEpoch=2L;BootstrapCount=2L;EventCount=2L;DisconnectCount=1L;ReconciliationCount=3L;ContractStateSha256=$s4;AcceptedEventKind='pane.agent_status_changed';AcceptedAgentStatusEvent=$accepted})
    $core=[ordered]@{EvidenceClassification='Runtime';RuntimeObserved=$true;SessionControlInvoked=$false;SnapshotObserved=$true;EventObserved=$true;ReconnectObserved=$true;Transitions=$transitions;Admission=[ordered]@{ReleaseId='0.8.2-synthetic-x86_64-pc-windows-msvc';ExecutableSha256=('D'*64);BundledSchemaSha256=('A'*64);Protocol=20}}
    $appPath=Join-Path $Root 'app-runtime.json';$corePath=Join-Path $Root 'core-runtime.json';Write-TestText $appPath ($app|ConvertTo-Json -Depth 12);Write-TestText $corePath ($core|ConvertTo-Json -Depth 8)
    $phases=@('waiting-for-live-state','capturing-live-dashboard-and-widgets','waiting-for-pre-close-update','dashboard-closed-waiting-for-herdr-disconnect','herdr-disconnected-waiting-for-reconnect','herdr-reconnected-waiting-for-post-reconnect-update','waiting-for-idle-stability','measuring-idle-resources','complete');$history=@();$previous='0'*64
    $seq=@(0L,1L,1L,2L,2L,3L,5L,5L,5L);$connected=@($false,$true,$true,$true,$false,$true,$true,$true,$true);$statuses=@('Starting','Connected','Connected','Connected','Reconnecting','Connected','Connected','Connected','Connected')
    for($i=0;$i-lt9;$i++){$entry=[ordered]@{Ordinal=($i+1);Phase=$phases[$i];ObservedUtc=([DateTimeOffset]::Parse('2026-08-22T00:00:00Z').AddSeconds($i).ToString('O'));Sequence=$seq[$i];IsCoreConnected=$connected[$i];IsLive=$connected[$i];RuntimeStatus=$statuses[$i];LastTransitionUtc='2026-08-22T00:00:00.0000000+00:00';LastAcceptedStateUtc=$null;ConnectionEpoch=$(if($i-lt5){1L}else{2L});BootstrapCount=$(if($i-lt5){1L}else{2L});EventCount=$(if($i-lt3){0L}elseif($i-lt6){1L}else{2L});DisconnectCount=$(if($i-lt4){0L}else{1L});ReconciliationCount=[long]$i;StateSha256=$(if($i-lt3){$s1}elseif($i-lt6){$s2}else{$s4});PreviousEntrySha256=$previous};$entry.CanonicalPayload=ProgressPayload ([pscustomobject]$entry);$entry.EntrySha256=TextHash $entry.CanonicalPayload;$previous=$entry.EntrySha256;$history+=[pscustomobject]$entry}
    $historyPath=Join-Path $Root 'app-progress.json.history.jsonl';Write-TestText $historyPath (($history|ForEach-Object{$_|ConvertTo-Json -Compress -Depth 8})-join[Environment]::NewLine);$progress=[ordered]@{};foreach($p in $history[8].PSObject.Properties){$progress[$p.Name]=$p.Value};$progress.ProgressHistoryPath=[IO.Path]::GetFullPath($historyPath);$progress.History=$history;$progressPath=Join-Path $Root 'app-progress.json';Write-TestText $progressPath ($progress|ConvertTo-Json -Depth 12)
    $lines=@('HerdrOps v0.2 Composite Actual Herdr Runtime Acceptance',"ExpectedSourceCommit: $Commit","ExpectedSourceTree: $Tree","SourceCommit: $Commit","SourceTree: $Tree","PreRunSourceCommit: $Commit","PreRunSourceTree: $Tree",'PreRunGitTreeClean: True',"PostRunSourceCommit: $Commit","PostRunSourceTree: $Tree",'PostRunGitTreeClean: True',"Result: $Result",'EvidenceClass: Runtime','SessionControlInvoked: false',"Language: $AppLanguage","PackageIdentityPath: $($script:packageFixture.IdentityPath)","PackageIdentityReceiptSha256: $($script:packageFixture.ReceiptSha256)","PackageArchivePath: $($script:packageFixture.ArchivePath)","PackageArchiveSha256: $($script:packageFixture.ArchiveSha256)","ExtractedPackageRoot: $($script:packageFixture.PackageRoot)","PackageManifestSha256: $($script:packageFixture.ManifestSha256)","AppSha256: $AppBinary","CoreSha256: $CoreBinary","PackageProfileId: $($script:packageFixture.ProfileId)",'PackageValidationEvidenceClass: Static/PackagedCompatibilityPreparation','HerdrReleaseId: 0.8.2-synthetic-x86_64-pc-windows-msvc',('HerdrExecutableSha256: '+('D'*64)),"HerdrOpsCoreExecutableSha256BeforeLaunch: $CoreBinary","HerdrOpsCoreExecutableSha256AfterRun: $CoreBinary","HerdrOpsAppExecutableSha256BeforeLaunch: $AppBinary","HerdrOpsAppExecutableSha256AfterRun: $AppBinary","HerdrOpsCoreExecutableSha256BoundToReports: $CoreBinary","HerdrOpsAppExecutableSha256BoundToReports: $AppBinary","CoreRuntimeReportSha256: $(Hash $corePath)","AppRuntimeReportSha256: $(Hash $appPath)","ProgressHistoryPath: $([IO.Path]::GetFullPath($historyPath))","ProgressHistorySha256: $(Hash $historyPath)",'ProgressHistoryEntries: 9',"ProgressHistoryLastEntrySha256: $previous",('BundledSchemaSha256: '+('A'*64)),'HerdrProtocol: 20',"ReferenceHostProfileId: $ProfileId","ReferenceHostProfileSha256: $ProfileSha","ReferenceHostSchemaSha256: $ReferenceSchemaSha",'RendererPolicyId: software-only-process-wide','WpfProcessRenderMode: SoftwareOnly','SoftwareOnlyThroughout: True','SnapshotObserved: True','EventObserved: True','ReconnectObserved: True','DashboardClosedUtc: 2026-08-22T00:00:02Z','DisconnectObservedUtc: 2026-08-22T00:00:03Z','ReconnectObservedUtc: 2026-08-22T00:00:04Z','RuntimeWpfCaptures: 8','','CaptureHashes:')
    $lines+=@($captures|ForEach-Object{"SHA256 $($_.Sha256) $($_.Name)"});Write-TestText (Join-Path $Root 'gate-report.txt') ($lines-join [Environment]::NewLine)
    return [pscustomobject]@{Root=$Root;AppPath=$appPath;CorePath=$corePath;ProgressPath=$progressPath;HistoryPath=$historyPath;CaptureRoot=$captureRoot}
}
function Invoke-Matrix([string]$Thai,[string]$English,[string]$Output){$all=@('-NoProfile','-File',$tool,'-ThaiEvidenceDirectory',$Thai,'-EnglishEvidenceDirectory',$English,'-PackageIdentityPath',$script:packageFixture.IdentityPath,'-PackageArchivePath',$script:packageFixture.ArchivePath,'-ExtractedPackageRoot',$script:packageFixture.PackageRoot,'-RepositoryRoot',$script:packageFixture.RepositoryRoot,'-PackageProfilePath',$script:packageFixture.ProfilePath,'-OutputPath',$Output);$previous=$ErrorActionPreference;$ErrorActionPreference='Continue';try{$text=@(& $engine @all 2>&1);$code=$LASTEXITCODE}finally{$ErrorActionPreference=$previous;$global:LASTEXITCODE=0};[pscustomobject]@{ExitCode=$code;Text=($text-join [Environment]::NewLine)}}
function Set-GateField($Fixture,[string]$Name,[string]$Value){$path=Join-Path $Fixture.Root 'gate-report.txt';$text=Get-Content -LiteralPath $path -Raw;$updated=[regex]::Replace($text,"(?m)^$([regex]::Escape($Name)): .+$","${Name}: $Value");if($updated-ceq$text){throw "Gate field was not found: $Name"};Write-TestText $path $updated}
function Refresh-AppHash($Fixture){Set-GateField $Fixture 'AppRuntimeReportSha256' (Hash $Fixture.AppPath)}
function Refresh-CoreHash($Fixture){Set-GateField $Fixture 'CoreRuntimeReportSha256' (Hash $Fixture.CorePath)}
function Rebind-FirstCapture($Fixture,[string]$Path){$app=Get-Content $Fixture.AppPath -Raw|ConvertFrom-Json;$capture=$app.Captures[0];$old=$capture.Sha256;$capture.Path=[IO.Path]::GetFullPath($Path);$capture.Sha256=Hash $Path;Write-TestText $Fixture.AppPath ($app|ConvertTo-Json -Depth 12);Refresh-AppHash $Fixture;$gate=Get-Content (Join-Path $Fixture.Root 'gate-report.txt') -Raw;$gate=$gate.Replace("SHA256 $old $($capture.Name)","SHA256 $($capture.Sha256) $($capture.Name)");Write-TestText (Join-Path $Fixture.Root 'gate-report.txt') $gate}
function Rechain-Progress($Fixture,[scriptblock]$Mutation){$entries=@([IO.File]::ReadAllLines($Fixture.HistoryPath)|ForEach-Object{$_|ConvertFrom-Json});&$Mutation $entries;$previous='0'*64;foreach($entry in $entries){$entry.PreviousEntrySha256=$previous;$entry.CanonicalPayload=ProgressPayload $entry;$entry.EntrySha256=TextHash $entry.CanonicalPayload;$previous=$entry.EntrySha256};Write-TestText $Fixture.HistoryPath (($entries|ForEach-Object{$_|ConvertTo-Json -Compress -Depth 8})-join[Environment]::NewLine);$progress=Get-Content $Fixture.ProgressPath -Raw|ConvertFrom-Json;foreach($property in $entries[8].PSObject.Properties){$progress.($property.Name)=$property.Value};$progress.History=$entries;Write-TestText $Fixture.ProgressPath ($progress|ConvertTo-Json -Depth 12);Set-GateField $Fixture 'ProgressHistorySha256' (Hash $Fixture.HistoryPath);Set-GateField $Fixture 'ProgressHistoryLastEntrySha256' $previous}
function Pass([string]$Name,[scriptblock]$Body){&$Body;Write-Output "PASS Synthetic: $Name"}
function Expect-Failure([string]$Name,[scriptblock]$Arrange){$case=Join-Path $testRoot ([Guid]::NewGuid().ToString('N'));$thai=New-RunFixture (Join-Path $case 'thai') 'Thai';$english=New-RunFixture (Join-Path $case 'english') 'English';&$Arrange $thai $english;$out=Join-Path $case 'matrix.json';$result=Invoke-Matrix $thai.Root $english.Root $out;if($result.ExitCode-eq 0-or(Test-Path $out)){throw "$Name did not fail closed. $($result.Text)"};Write-Output "PASS Synthetic: $Name"}

try {
    Pass 'happy path emits hash-bound non-release candidate' {
        $case=Join-Path $testRoot 'happy';$thai=New-RunFixture (Join-Path $case 'thai') 'Thai';$english=New-RunFixture (Join-Path $case 'english') 'English';$out=Join-Path $case 'matrix.json';$result=Invoke-Matrix $thai.Root $english.Root $out
        if($result.ExitCode-ne 0){throw $result.Text};$manifest=Get-Content $out -Raw|ConvertFrom-Json
        if($manifest.EvidenceClassification-cne'RuntimeMatrixCandidate'-or$manifest.IndependentHumanReview-cne'NOT_OBSERVED'-or[bool]$manifest.ReleaseCredit-or$manifest.Payload.IndependentHumanReview-cne'NOT_OBSERVED'-or[bool]$manifest.Payload.ReleaseCredit){throw 'Happy manifest boundary fields are wrong.'}
        $payloadJson=ConvertTo-V02Jcs $manifest.Payload;$observed=([BitConverter]::ToString([Security.Cryptography.SHA256]::Create().ComputeHash($utf8.GetBytes($payloadJson)))).Replace('-','');if($observed-cne[string]$manifest.ManifestPayloadSha256){throw 'Manifest payload SHA mismatch.'}
    }
    foreach($caseInfo in @(
        @{Name='mixed source commit';Args=@{Commit=('c'*40)}},
        @{Name='mixed source tree';Args=@{Tree=('d'*40)}},
        @{Name='mixed App binary';Args=@{AppBinary=('B'*64)}},
        @{Name='mixed profile hash';Args=@{ProfileSha=('B'*64)}})) {
        $case=Join-Path $testRoot ([Guid]::NewGuid().ToString('N'));$thai=New-RunFixture (Join-Path $case 'thai') 'Thai';$fixtureArgs=$caseInfo.Args;$english=New-RunFixture -Root (Join-Path $case 'english') -Language 'English' @fixtureArgs;$out=Join-Path $case 'matrix.json';$result=Invoke-Matrix $thai.Root $english.Root $out;if($result.ExitCode-eq 0-or(Test-Path $out)){throw "$($caseInfo.Name) did not fail closed."};Write-Output "PASS Synthetic: $($caseInfo.Name)"
    }
    Expect-Failure 'swapped Thai language' {param($thai,$english);$replacement=New-RunFixture -Root $thai.Root -Language Thai -AppLanguage English}
    Expect-Failure 'duplicate Thai language' {param($thai,$english);$replacement=New-RunFixture -Root $english.Root -Language English -AppLanguage Thai}
    Pass 'same evidence directory rejected' {$case=Join-Path $testRoot 'same-dir';$thai=New-RunFixture $case 'Thai';$out=Join-Path $testRoot 'same-dir-output.json';$result=Invoke-Matrix $thai.Root $thai.Root $out;if($result.ExitCode-eq 0-or(Test-Path $out)){throw 'Same evidence directory did not fail closed.'}}
    Expect-Failure 'shared capture paths rejected' {param($thai,$english);$app=Get-Content $english.AppPath -Raw|ConvertFrom-Json;$thaiApp=Get-Content $thai.AppPath -Raw|ConvertFrom-Json;for($i=0;$i-lt$app.Captures.Count;$i++){$app.Captures[$i].Path=$thaiApp.Captures[$i].Path;$app.Captures[$i].Sha256=$thaiApp.Captures[$i].Sha256};Write-TestText $english.AppPath ($app|ConvertTo-Json -Depth 12);$gate=Get-Content (Join-Path $english.Root 'gate-report.txt') -Raw;$gate=[regex]::Replace($gate,'(?m)^AppRuntimeReportSha256: .+$',"AppRuntimeReportSha256: $(Hash $english.AppPath)");Write-TestText (Join-Path $english.Root 'gate-report.txt') $gate}
    Pass 'capture path escape rejected' {$case=Join-Path $testRoot ([Guid]::NewGuid().ToString('N'));$thai=New-RunFixture (Join-Path $case 'thai') Thai;$english=New-RunFixture (Join-Path $case 'english') English;$source=(Get-Content $english.AppPath -Raw|ConvertFrom-Json).Captures[0].Path;$outside=Join-Path $case 'escaped.png';Copy-Item -LiteralPath $source -Destination $outside;try{Rebind-FirstCapture $english $outside;$out=Join-Path $case 'matrix.json';$result=Invoke-Matrix $thai.Root $english.Root $out;if($result.ExitCode-eq0-or(Test-Path $out)){throw 'Capture path escape did not fail closed.'}}finally{if(Test-Path -LiteralPath $outside){Remove-Item -LiteralPath $outside -Force}}}
    Pass 'capture reparse component rejected' {$case=Join-Path $testRoot ([Guid]::NewGuid().ToString('N'));$thai=New-RunFixture (Join-Path $case 'thai') Thai;$english=New-RunFixture (Join-Path $case 'english') English;$target=Join-Path $case 'reparse-target';New-Item -ItemType Directory -Path $target|Out-Null;$source=(Get-Content $english.AppPath -Raw|ConvertFrom-Json).Captures[0].Path;$targetCapture=Join-Path $target 'escaped.png';Copy-Item -LiteralPath $source -Destination $targetCapture;$link=Join-Path $english.Root 'capture-link';New-Item -ItemType Junction -Path $link -Target $target|Out-Null;try{$linked=Join-Path $link 'escaped.png';Rebind-FirstCapture $english $linked;$out=Join-Path $case 'matrix.json';$result=Invoke-Matrix $thai.Root $english.Root $out;if($result.ExitCode-eq0-or(Test-Path $out)){throw 'Capture reparse component did not fail closed.'}}finally{if(Test-Path -LiteralPath $link){[IO.Directory]::Delete($link,$false)};if(Test-Path -LiteralPath $target){Remove-Item -LiteralPath $target -Recurse -Force}}}
    Pass 'oversized evidence rejected before allocation' {$case=Join-Path $testRoot ([Guid]::NewGuid().ToString('N'));$thai=New-RunFixture (Join-Path $case 'thai') Thai;$english=New-RunFixture (Join-Path $case 'english') English;$capturePath=(Get-Content $english.AppPath -Raw|ConvertFrom-Json).Captures[0].Path;$stream=[IO.File]::Open($capturePath,[IO.FileMode]::Open,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None);try{$stream.SetLength(16777217)}finally{$stream.Dispose()};$out=Join-Path $case 'matrix.json';$result=Invoke-Matrix $thai.Root $english.Root $out;if($result.ExitCode-eq0-or(Test-Path $out)){throw 'Oversized evidence did not fail closed.'}}
    Expect-Failure 'failed gate result rejected' {param($thai,$english);$gate=Get-Content (Join-Path $english.Root 'gate-report.txt') -Raw;$gate=$gate.Replace('Result: PASS','Result: FAIL');Write-TestText (Join-Path $english.Root 'gate-report.txt') $gate}
    Expect-Failure 'gate-declared report hash mismatch rejected' {param($thai,$english);$gate=Get-Content (Join-Path $english.Root 'gate-report.txt') -Raw;$gate=[regex]::Replace($gate,'(?m)^AppRuntimeReportSha256: .+$',('AppRuntimeReportSha256: '+('0'*64)));Write-TestText (Join-Path $english.Root 'gate-report.txt') $gate}
    Pass 'wrong but matching profile rejected' {$case=Join-Path $testRoot 'wrong-profile';$wrong=('B'*64);$thai=New-RunFixture -Root (Join-Path $case 'thai') -Language Thai -ProfileSha $wrong;$english=New-RunFixture -Root (Join-Path $case 'english') -Language English -ProfileSha $wrong;$out=Join-Path $case 'matrix.json';$result=Invoke-Matrix $thai.Root $english.Root $out;if($result.ExitCode-eq 0-or(Test-Path $out)){throw 'Matching unapproved profile did not fail closed.'}}
    Pass 'wrong but matching reference-host schema rejected' {$case=Join-Path $testRoot 'wrong-schema';$wrong=('B'*64);$thai=New-RunFixture -Root (Join-Path $case 'thai') -Language Thai -ReferenceSchemaSha $wrong;$english=New-RunFixture -Root (Join-Path $case 'english') -Language English -ReferenceSchemaSha $wrong;$out=Join-Path $case 'matrix.json';$result=Invoke-Matrix $thai.Root $english.Root $out;if($result.ExitCode-eq 0-or(Test-Path $out)){throw 'Matching unapproved reference-host schema did not fail closed.'}}
    Pass 'output inside accepted evidence rejected' {$case=Join-Path $testRoot 'inside-output';$thai=New-RunFixture (Join-Path $case 'thai') Thai;$english=New-RunFixture (Join-Path $case 'english') English;$out=Join-Path $thai.Root 'matrix.json';$result=Invoke-Matrix $thai.Root $english.Root $out;if($result.ExitCode-eq 0-or(Test-Path $out)){throw 'Output inside accepted evidence did not fail closed.'}}
    Pass 'output parent escape rejected' {$case=Join-Path $testRoot ([Guid]::NewGuid().ToString('N'));$thai=New-RunFixture (Join-Path $case 'thai') Thai;$english=New-RunFixture (Join-Path $case 'english') English;$out=Join-Path (Split-Path $case -Parent) ('matrix-escape-'+[Guid]::NewGuid().ToString('N')+'.json');$result=Invoke-Matrix $thai.Root $english.Root $out;if($result.ExitCode-eq0-or(Test-Path $out)){throw 'Output parent escape did not fail closed.'};if(Test-Path -LiteralPath $out){Remove-Item -LiteralPath $out -Force}}
    Pass 'existing output is not clobbered' {$case=Join-Path $testRoot ([Guid]::NewGuid().ToString('N'));$thai=New-RunFixture (Join-Path $case 'thai') Thai;$english=New-RunFixture (Join-Path $case 'english') English;$out=Join-Path $case 'existing.json';Write-TestText $out 'sentinel';$result=Invoke-Matrix $thai.Root $english.Root $out;if($result.ExitCode-eq0){throw 'Existing output was accepted.'};if((Get-Content -LiteralPath $out -Raw)-cne'sentinel'){throw 'Existing output was clobbered.'}}
    Pass 'reparse output parent rejected' {$case=Join-Path $testRoot ([Guid]::NewGuid().ToString('N'));$thai=New-RunFixture (Join-Path $case 'thai') Thai;$english=New-RunFixture (Join-Path $case 'english') English;$target=Join-Path $case 'output-target';New-Item -ItemType Directory -Path $target|Out-Null;$link=Join-Path $case 'output-link';New-Item -ItemType Junction -Path $link -Target $target|Out-Null;try{$out=Join-Path $link 'candidate.json';$result=Invoke-Matrix $thai.Root $english.Root $out;if($result.ExitCode-eq0-or(Test-Path $out)){throw 'Reparse output parent did not fail closed.'}}finally{if(Test-Path -LiteralPath $link){[IO.Directory]::Delete($link,$false)};if(Test-Path -LiteralPath $target){Remove-Item -LiteralPath $target -Recurse -Force}}}
    Expect-Failure 'post-run final language tamper rejected after report rehash' {param($thai,$english);$app=Get-Content $english.AppPath -Raw|ConvertFrom-Json;$app.FinalLanguage='Thai';Write-TestText $english.AppPath ($app|ConvertTo-Json -Depth 12);Refresh-AppHash $english}
    Expect-Failure 'post-run language culture tamper rejected after report rehash' {param($thai,$english);$app=Get-Content $english.AppPath -Raw|ConvertFrom-Json;$app.FinalLanguageCultureName='th-TH';Write-TestText $english.AppPath ($app|ConvertTo-Json -Depth 12);Refresh-AppHash $english}
    Expect-Failure 'post-run capture state tamper rejected after report rehash' {param($thai,$english);$app=Get-Content $english.AppPath -Raw|ConvertFrom-Json;$app.Captures[0].StateSha256='2'*64;Write-TestText $english.AppPath ($app|ConvertTo-Json -Depth 12);Refresh-AppHash $english}
    Expect-Failure 'post-run accepted-event kind tamper rejected after report rehash' {param($thai,$english);$core=Get-Content $english.CorePath -Raw|ConvertFrom-Json;$core.Transitions[1].AcceptedEventKind='pane.title_changed';Write-TestText $english.CorePath ($core|ConvertTo-Json -Depth 12);Refresh-CoreHash $english}
    Expect-Failure 'post-run RuntimeObserved tamper rejected after report rehash' {param($thai,$english);$core=Get-Content $english.CorePath -Raw|ConvertFrom-Json;$core.RuntimeObserved=$false;Write-TestText $english.CorePath ($core|ConvertTo-Json -Depth 12);Refresh-CoreHash $english}
    Expect-Failure 'post-run JSONL chain tamper rejected after history rehash' {param($thai,$english);$lines=[IO.File]::ReadAllLines($english.HistoryPath);$entry=$lines[4]|ConvertFrom-Json;$entry.EventCount=99;$lines[4]=$entry|ConvertTo-Json -Compress -Depth 8;Write-TestText $english.HistoryPath ($lines-join[Environment]::NewLine);Set-GateField $english 'ProgressHistorySha256' (Hash $english.HistoryPath)}
    Expect-Failure 'post-run app-progress mirror tamper rejected' {param($thai,$english);$progress=Get-Content $english.ProgressPath -Raw|ConvertFrom-Json;$progress.History[2].Phase='tampered';Write-TestText $english.ProgressPath ($progress|ConvertTo-Json -Depth 12)}
    Expect-Failure 'different package receipt rejected' {param($thai,$english);Set-GateField $english 'PackageIdentityReceiptSha256' ('8'*64)}
    Expect-Failure 'post-run truncated PNG rejected after capture rehash' {param($thai,$english);$app=Get-Content $english.AppPath -Raw|ConvertFrom-Json;$capture=$app.Captures[0];$old=$capture.Sha256;[IO.File]::WriteAllBytes($capture.Path,[byte[]](137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,2,0,0,0,2));$capture.Sha256=Hash $capture.Path;Write-TestText $english.AppPath ($app|ConvertTo-Json -Depth 12);Refresh-AppHash $english;$gate=Get-Content (Join-Path $english.Root 'gate-report.txt') -Raw;$gate=$gate.Replace("SHA256 $old $($capture.Name)","SHA256 $($capture.Sha256) $($capture.Name)");Write-TestText (Join-Path $english.Root 'gate-report.txt') $gate}
    Expect-Failure 'native LanguageChangeCount double rejected after report rehash' {param($thai,$english);$json=Get-Content $english.AppPath -Raw;$json=[regex]::Replace($json,'("LanguageChangeCount"\s*:\s*)0([,\r\n])','${1}0.0${2}');Write-TestText $english.AppPath $json;Refresh-AppHash $english}
    Expect-Failure 'reconnect-before-disconnect chronology rejected after report rehash' {param($thai,$english);$app=Get-Content $english.AppPath -Raw|ConvertFrom-Json;$app.ReconnectObservedUtc='2026-08-22T00:00:01Z';Write-TestText $english.AppPath ($app|ConvertTo-Json -Depth 12);Refresh-AppHash $english}
    Expect-Failure 'rehashed contradictory App Core reconnect counter rejected' {param($thai,$english);$app=Get-Content $english.AppPath -Raw|ConvertFrom-Json;$app.ReconnectedConnectionEpoch=3;Write-TestText $english.AppPath ($app|ConvertTo-Json -Depth 12);Refresh-AppHash $english}
    Expect-Failure 'fully rechained backward progress timestamp rejected' {param($thai,$english);Rechain-Progress $english {param($entries);$entries[5].ObservedUtc='2026-08-21T00:00:00Z'}}
    Pass 'tampered package archive rejected by independent validator' {$saved=[IO.File]::ReadAllBytes($script:packageFixture.ArchivePath);try{[IO.File]::AppendAllText($script:packageFixture.ArchivePath,'tamper');$case=Join-Path $testRoot 'archive-tamper';$thai=New-RunFixture (Join-Path $case 'thai') Thai;$english=New-RunFixture (Join-Path $case 'english') English;$result=Invoke-Matrix $thai.Root $english.Root (Join-Path $case 'matrix.json');if($result.ExitCode-eq0){throw 'Tampered package archive passed.'}}finally{[IO.File]::WriteAllBytes($script:packageFixture.ArchivePath,$saved)}}
    Write-Output 'All 34 v0.2 language-matrix cases passed. EvidenceClass: Synthetic.'
} finally {
    if(Test-Path -LiteralPath $testRoot){Remove-Item -LiteralPath $testRoot -Recurse -Force}
}
